/*[============== selection data  ==============]*/

/*--------- Family Data --------------*/ 
export const fontFamilyData = [
    {
        title: 'Family',
        key: 'family',
        selectData: [
            {innerText: 'Arial', value: 'Arial'},
            {innerText: 'Tahoma', value: 'Tahoma'},
            {innerText: 'Verdana', value: 'Verdana'},
            {innerText: 'Helvetica', value: 'Helvetica'},
            {innerText: 'Times New Roman', value: 'Times New Roman'},
            {innerText: 'Trebuchet MS', value: 'Trebuchet MS'},
            {innerText: 'Georgia', value: 'Georgia'},
            {innerText: 'ABeeZee', value: 'ABeeZee'},
            {innerText: 'Abel', value: 'Abel'},
            {innerText: 'Abhaya Libre', value: 'Abhaya Libre'},
            {innerText: 'Aboreto', value: 'Aboreto'},
            {innerText: 'Abril Fatface', value: 'Abril Fatface'},
            {innerText: 'Abyssinica SIL', value: 'Abyssinica SIL'},
            {innerText: 'Aclonica', value: 'Aclonica'},
            {innerText: 'Acme', value: 'Acme'},
            {innerText: 'Actor', value: 'Actor'},
            {innerText: 'Adamina', value: 'Adamina'},
            {innerText: 'Advent Pro', value: 'Advent Pro'},
            {innerText: 'Aguafina Script', value: 'Aguafina Script'},
            {innerText: 'Akaya Kanadaka', value: 'Akaya Kanadaka'},
            {innerText: 'Akaya Telivigala', value: 'Akaya Telivigala'},
            {innerText: 'Akronim', value: 'Akronim'},
            {innerText: 'Akshar', value: 'Akshar'},
            {innerText: 'Aladin', value: 'Aladin'},
            {innerText: 'Alata', value: 'Alata'},
            {innerText: 'Alatsi', value: 'Alatsi'},
            {innerText: 'Albert Sans', value: 'Albert Sans'},
            {innerText: 'Aldrich', value: 'Aldrich'},
            {innerText: 'Alef', value: 'Alef'},
            {innerText: 'Alegreya', value: 'Alegreya'},
            {innerText: 'Alegreya SC', value: 'Alegreya SC'},
            {innerText: 'Alegreya Sans', value: 'Alegreya Sans'},
            {innerText: 'Alegreya Sans SC', value: 'Alegreya Sans SC'},
            {innerText: 'Aleo', value: 'Aleo'},
            {innerText: 'Alex Brush', value: 'Alex Brush'},
            {innerText: 'Alexandria', value: 'Alexandria'},
            {innerText: 'Alfa Slab One', value: 'Alfa Slab One'},
            {innerText: 'Alice', value: 'Alice'},
            {innerText: 'Alike', value: 'Alike'},
            {innerText: 'Alike Angular', value: 'Alike Angular'},
            {innerText: 'Alkalami', value: 'Alkalami'},
            {innerText: 'Allan', value: 'Allan'},
            {innerText: 'Allerta', value: 'Allerta'},
            {innerText: 'Allerta Stencil', value: 'Allerta Stencil'},
            {innerText: 'Allison', value: 'Allison'},
            {innerText: 'Allura', value: 'Allura'},
            {innerText: 'Almarai', value: 'Almarai'},
            {innerText: 'Almendra', value: 'Almendra'},
            {innerText: 'Almendra Display', value: 'Almendra Display'},
            {innerText: 'Almendra SC', value: 'Almendra SC'},
            {innerText: 'Alumni Sans', value: 'Alumni Sans'},
            {innerText: 'Alumni Sans Collegiate One', value: 'Alumni Sans Collegiate One'},
            {innerText: 'Alumni Sans Inline One', value: 'Alumni Sans Inline One'},
            {innerText: 'Alumni Sans Pinstripe', value: 'Alumni Sans Pinstripe'},
            {innerText: 'Amarante', value: 'Amarante'},
            {innerText: 'Amaranth', value: 'Amaranth'},
            {innerText: 'Amatic SC', value: 'Amatic SC'},
            {innerText: 'Amethysta', value: 'Amethysta'},
            {innerText: 'Amiko', value: 'Amiko'},
            {innerText: 'Amiri', value: 'Amiri'},
            {innerText: 'Amiri Quran', value: 'Amiri Quran'},
            {innerText: 'Amita', value: 'Amita'},
            {innerText: 'Anaheim', value: 'Anaheim'},
            {innerText: 'Andada Pro', value: 'Andada Pro'},
            {innerText: 'Andika', value: 'Andika'},
            {innerText: 'Anek Bangla', value: 'Anek Bangla'},
            {innerText: 'Anek Devanagari', value: 'Anek Devanagari'},
            {innerText: 'Anek Gujarati', value: 'Anek Gujarati'},
            {innerText: 'Anek Gurmukhi', value: 'Anek Gurmukhi'},
            {innerText: 'Anek Kannada', value: 'Anek Kannada'},
            {innerText: 'Anek Latin', value: 'Anek Latin'},
            {innerText: 'Anek Malayalam', value: 'Anek Malayalam'},
            {innerText: 'Anek Odia', value: 'Anek Odia'},
            {innerText: 'Anek Tamil', value: 'Anek Tamil'},
            {innerText: 'Anek Telugu', value: 'Anek Telugu'},
            {innerText: 'Angkor', value: 'Angkor'},
            {innerText: 'Annie Use Your Telescope', value: 'Annie Use Your Telescope'},
            {innerText: 'Anonymous Pro', value: 'Anonymous Pro'},
            {innerText: 'Antic', value: 'Antic'},
            {innerText: 'Antic Didone', value: 'Antic Didone'},
            {innerText: 'Antic Slab', value: 'Antic Slab'},
            {innerText: 'Anton', value: 'Anton'},
            {innerText: 'Antonio', value: 'Antonio'},
            {innerText: 'Anybody', value: 'Anybody'},
            {innerText: 'Arapey', value: 'Arapey'},
            {innerText: 'Arbutus', value: 'Arbutus'},
            {innerText: 'Arbutus Slab', value: 'Arbutus Slab'},
            {innerText: 'Architects Daughter', value: 'Architects Daughter'},
            {innerText: 'Archivo', value: 'Archivo'},
            {innerText: 'Archivo Black', value: 'Archivo Black'},
            {innerText: 'Archivo Narrow', value: 'Archivo Narrow'},
            {innerText: 'Are You Serious', value: 'Are You Serious'},
            {innerText: 'Aref Ruqaa', value: 'Aref Ruqaa'},
            {innerText: 'Aref Ruqaa Ink', value: 'Aref Ruqaa Ink'},
            {innerText: 'Arima', value: 'Arima'},
            {innerText: 'Arima Madurai', value: 'Arima Madurai'},
            {innerText: 'Arimo', value: 'Arimo'},
            {innerText: 'Arizonia', value: 'Arizonia'},
            {innerText: 'Armata', value: 'Armata'},
            {innerText: 'Arsenal', value: 'Arsenal'},
            {innerText: 'Artifika', value: 'Artifika'},
            {innerText: 'Arvo', value: 'Arvo'},
            {innerText: 'Arya', value: 'Arya'},
            {innerText: 'Asap', value: 'Asap'},
            {innerText: 'Asap Condensed', value: 'Asap Condensed'},
            {innerText: 'Asar', value: 'Asar'},
            {innerText: 'Asset', value: 'Asset'},
            {innerText: 'Assistant', value: 'Assistant'},
            {innerText: 'Astloch', value: 'Astloch'},
            {innerText: 'Asul', value: 'Asul'},
            {innerText: 'Athiti', value: 'Athiti'},
            {innerText: 'Atkinson Hyperlegible', value: 'Atkinson Hyperlegible'},
            {innerText: 'Atma', value: 'Atma'},
            {innerText: 'Atomic Age', value: 'Atomic Age'},
            {innerText: 'Aubrey', value: 'Aubrey'},
            {innerText: 'Audiowide', value: 'Audiowide'},
            {innerText: 'Autour One', value: 'Autour One'},
            {innerText: 'Average', value: 'Average'},
            {innerText: 'Average Sans', value: 'Average Sans'},
            {innerText: 'Averia Gruesa Libre', value: 'Averia Gruesa Libre'},
            {innerText: 'Averia Libre', value: 'Averia Libre'},
            {innerText: 'Averia Sans Libre', value: 'Averia Sans Libre'},
            {innerText: 'Averia Serif Libre', value: 'Averia Serif Libre'},
            {innerText: 'Azeret Mono', value: 'Azeret Mono'},
            {innerText: 'B612', value: 'B612'},
            {innerText: 'B612 Mono', value: 'B612 Mono'},
            {innerText: 'BIZ UDGothic', value: 'BIZ UDGothic'},
            {innerText: 'BIZ UDMincho', value: 'BIZ UDMincho'},
            {innerText: 'BIZ UDPGothic', value: 'BIZ UDPGothic'},
            {innerText: 'BIZ UDPMincho', value: 'BIZ UDPMincho'},
            {innerText: 'Babylonica', value: 'Babylonica'},
            {innerText: 'Bad Script', value: 'Bad Script'},
            {innerText: 'Bahiana', value: 'Bahiana'},
            {innerText: 'Bahianita', value: 'Bahianita'},
            {innerText: 'Bai Jamjuree', value: 'Bai Jamjuree'},
            {innerText: 'Bakbak One', value: 'Bakbak One'},
            {innerText: 'Ballet', value: 'Ballet'},
            {innerText: 'Baloo 2', value: 'Baloo 2'},
            {innerText: 'Baloo Bhai 2', value: 'Baloo Bhai 2'},
            {innerText: 'Baloo Bhaijaan 2', value: 'Baloo Bhaijaan 2'},
            {innerText: 'Baloo Bhaina 2', value: 'Baloo Bhaina 2'},
            {innerText: 'Baloo Chettan 2', value: 'Baloo Chettan 2'},
            {innerText: 'Baloo Da 2', value: 'Baloo Da 2'},
            {innerText: 'Baloo Paaji 2', value: 'Baloo Paaji 2'},
            {innerText: 'Baloo Tamma 2', value: 'Baloo Tamma 2'},
            {innerText: 'Baloo Tammudu 2', value: 'Baloo Tammudu 2'},
            {innerText: 'Baloo Thambi 2', value: 'Baloo Thambi 2'},
            {innerText: 'Balsamiq Sans', value: 'Balsamiq Sans'},
            {innerText: 'Balthazar', value: 'Balthazar'},
            {innerText: 'Bangers', value: 'Bangers'},
            {innerText: 'Barlow', value: 'Barlow'},
            {innerText: 'Barlow Condensed', value: 'Barlow Condensed'},
            {innerText: 'Barlow Semi Condensed', value: 'Barlow Semi Condensed'},
            {innerText: 'Barriecito', value: 'Barriecito'},
            {innerText: 'Barrio', value: 'Barrio'},
            {innerText: 'Basic', value: 'Basic'},
            {innerText: 'Baskervville', value: 'Baskervville'},
            {innerText: 'Battambang', value: 'Battambang'},
            {innerText: 'Baumans', value: 'Baumans'},
            {innerText: 'Bayon', value: 'Bayon'},
            {innerText: 'Be Vietnam Pro', value: 'Be Vietnam Pro'},
            {innerText: 'Beau Rivage', value: 'Beau Rivage'},
            {innerText: 'Bebas Neue', value: 'Bebas Neue'},
            {innerText: 'Belgrano', value: 'Belgrano'},
            {innerText: 'Bellefair', value: 'Bellefair'},
            {innerText: 'Belleza', value: 'Belleza'},
            {innerText: 'Bellota', value: 'Bellota'},
            {innerText: 'Bellota Text', value: 'Bellota Text'},
            {innerText: 'BenchNine', value: 'BenchNine'},
            {innerText: 'Benne', value: 'Benne'},
            {innerText: 'Bentham', value: 'Bentham'},
            {innerText: 'Berkshire Swash', value: 'Berkshire Swash'},
            {innerText: 'Besley', value: 'Besley'},
            {innerText: 'Beth Ellen', value: 'Beth Ellen'},
            {innerText: 'Bevan', value: 'Bevan'},
            {innerText: 'BhuTuka Expanded One', value: 'BhuTuka Expanded One'},
            {innerText: 'Big Shoulders Display', value: 'Big Shoulders Display'},
            {innerText: 'Big Shoulders Inline Display', value: 'Big Shoulders Inline Display'},
            {innerText: 'Big Shoulders Inline Text', value: 'Big Shoulders Inline Text'},
            {innerText: 'Big Shoulders Stencil Display', value: 'Big Shoulders Stencil Display'},
            {innerText: 'Big Shoulders Stencil Text', value: 'Big Shoulders Stencil Text'},
            {innerText: 'Big Shoulders Text', value: 'Big Shoulders Text'},
            {innerText: 'Bigelow Rules', value: 'Bigelow Rules'},
            {innerText: 'Bigshot One', value: 'Bigshot One'},
            {innerText: 'Bilbo', value: 'Bilbo'},
            {innerText: 'Bilbo Swash Caps', value: 'Bilbo Swash Caps'},
            {innerText: 'BioRhyme', value: 'BioRhyme'},
            {innerText: 'BioRhyme Expanded', value: 'BioRhyme Expanded'},
            {innerText: 'Birthstone', value: 'Birthstone'},
            {innerText: 'Birthstone Bounce', value: 'Birthstone Bounce'},
            {innerText: 'Biryani', value: 'Biryani'},
            {innerText: 'Bitter', value: 'Bitter'},
            {innerText: 'Black And White Picture', value: 'Black And White Picture'},
            {innerText: 'Black Han Sans', value: 'Black Han Sans'},
            {innerText: 'Black Ops One', value: 'Black Ops One'},
            {innerText: 'Blaka', value: 'Blaka'},
            {innerText: 'Blaka Hollow', value: 'Blaka Hollow'},
            {innerText: 'Blaka Ink', value: 'Blaka Ink'},
            {innerText: 'Blinker', value: 'Blinker'},
            {innerText: 'Bodoni Moda', value: 'Bodoni Moda'},
            {innerText: 'Bokor', value: 'Bokor'},
            {innerText: 'Bona Nova', value: 'Bona Nova'},
            {innerText: 'Bonbon', value: 'Bonbon'},
            {innerText: 'Bonheur Royale', value: 'Bonheur Royale'},
            {innerText: 'Boogaloo', value: 'Boogaloo'},
            {innerText: 'Bowlby One', value: 'Bowlby One'},
            {innerText: 'Bowlby One SC', value: 'Bowlby One SC'},
            {innerText: 'Brawler', value: 'Brawler'},
            {innerText: 'Bree Serif', value: 'Bree Serif'},
            {innerText: 'Brygada 1918', value: 'Brygada 1918'},
            {innerText: 'Bubblegum Sans', value: 'Bubblegum Sans'},
            {innerText: 'Bubbler One', value: 'Bubbler One'},
            {innerText: 'Buda', value: 'Buda'},
            {innerText: 'Buenard', value: 'Buenard'},
            {innerText: 'Bungee', value: 'Bungee'},
            {innerText: 'Bungee Hairline', value: 'Bungee Hairline'},
            {innerText: 'Bungee Inline', value: 'Bungee Inline'},
            {innerText: 'Bungee Outline', value: 'Bungee Outline'},
            {innerText: 'Bungee Shade', value: 'Bungee Shade'},
            {innerText: 'Bungee Spice', value: 'Bungee Spice'},
            {innerText: 'Butcherman', value: 'Butcherman'},
            {innerText: 'Butterfly Kids', value: 'Butterfly Kids'},
            {innerText: 'Cabin', value: 'Cabin'},
            {innerText: 'Cabin Condensed', value: 'Cabin Condensed'},
            {innerText: 'Cabin Sketch', value: 'Cabin Sketch'},
            {innerText: 'Caesar Dressing', value: 'Caesar Dressing'},
            {innerText: 'Cagliostro', value: 'Cagliostro'},
            {innerText: 'Cairo', value: 'Cairo'},
            {innerText: 'Cairo Play', value: 'Cairo Play'},
            {innerText: 'Caladea', value: 'Caladea'},
            {innerText: 'Calistoga', value: 'Calistoga'},
            {innerText: 'Calligraffitti', value: 'Calligraffitti'},
            {innerText: 'Cambay', value: 'Cambay'},
            {innerText: 'Cambo', value: 'Cambo'},
            {innerText: 'Candal', value: 'Candal'},
            {innerText: 'Cantarell', value: 'Cantarell'},
            {innerText: 'Cantata One', value: 'Cantata One'},
            {innerText: 'Cantora One', value: 'Cantora One'},
            {innerText: 'Capriola', value: 'Capriola'},
            {innerText: 'Caramel', value: 'Caramel'},
            {innerText: 'Carattere', value: 'Carattere'},
            {innerText: 'Cardo', value: 'Cardo'},
            {innerText: 'Carme', value: 'Carme'},
            {innerText: 'Carrois Gothic', value: 'Carrois Gothic'},
            {innerText: 'Carrois Gothic SC', value: 'Carrois Gothic SC'},
            {innerText: 'Carter One', value: 'Carter One'},
            {innerText: 'Castoro', value: 'Castoro'},
            {innerText: 'Catamaran', value: 'Catamaran'},
            {innerText: 'Caudex', value: 'Caudex'},
            {innerText: 'Caveat', value: 'Caveat'},
            {innerText: 'Caveat Brush', value: 'Caveat Brush'},
            {innerText: 'Cedarville Cursive', value: 'Cedarville Cursive'},
            {innerText: 'Ceviche One', value: 'Ceviche One'},
            {innerText: 'Chakra Petch', value: 'Chakra Petch'},
            {innerText: 'Changa', value: 'Changa'},
            {innerText: 'Changa One', value: 'Changa One'},
            {innerText: 'Chango', value: 'Chango'},
            {innerText: 'Charis SIL', value: 'Charis SIL'},
            {innerText: 'Charm', value: 'Charm'},
            {innerText: 'Charmonman', value: 'Charmonman'},
            {innerText: 'Chathura', value: 'Chathura'},
            {innerText: 'Chau Philomene One', value: 'Chau Philomene One'},
            {innerText: 'Chela One', value: 'Chela One'},
            {innerText: 'Chelsea Market', value: 'Chelsea Market'},
            {innerText: 'Chenla', value: 'Chenla'},
            {innerText: 'Cherish', value: 'Cherish'},
            {innerText: 'Cherry Cream Soda', value: 'Cherry Cream Soda'},
            {innerText: 'Cherry Swash', value: 'Cherry Swash'},
            {innerText: 'Chewy', value: 'Chewy'},
            {innerText: 'Chicle', value: 'Chicle'},
            {innerText: 'Chilanka', value: 'Chilanka'},
            {innerText: 'Chivo', value: 'Chivo'},
            {innerText: 'Chivo Mono', value: 'Chivo Mono'},
            {innerText: 'Chonburi', value: 'Chonburi'},
            {innerText: 'Cinzel', value: 'Cinzel'},
            {innerText: 'Cinzel Decorative', value: 'Cinzel Decorative'},
            {innerText: 'Clicker Script', value: 'Clicker Script'},
            {innerText: 'Coda', value: 'Coda'},
            {innerText: 'Coda Caption', value: 'Coda Caption'},
            {innerText: 'Codystar', value: 'Codystar'},
            {innerText: 'Coiny', value: 'Coiny'},
            {innerText: 'Combo', value: 'Combo'},
            {innerText: 'Comfortaa', value: 'Comfortaa'},
            {innerText: 'Comforter', value: 'Comforter'},
            {innerText: 'Comforter Brush', value: 'Comforter Brush'},
            {innerText: 'Comic Neue', value: 'Comic Neue'},
            {innerText: 'Coming Soon', value: 'Coming Soon'},
            {innerText: 'Commissioner', value: 'Commissioner'},
            {innerText: 'Concert One', value: 'Concert One'},
            {innerText: 'Condiment', value: 'Condiment'},
            {innerText: 'Content', value: 'Content'},
            {innerText: 'Contrail One', value: 'Contrail One'},
            {innerText: 'Convergence', value: 'Convergence'},
            {innerText: 'Cookie', value: 'Cookie'},
            {innerText: 'Copse', value: 'Copse'},
            {innerText: 'Corben', value: 'Corben'},
            {innerText: 'Corinthia', value: 'Corinthia'},
            {innerText: 'Cormorant', value: 'Cormorant'},
            {innerText: 'Cormorant Garamond', value: 'Cormorant Garamond'},
            {innerText: 'Cormorant Infant', value: 'Cormorant Infant'},
            {innerText: 'Cormorant SC', value: 'Cormorant SC'},
            {innerText: 'Cormorant Unicase', value: 'Cormorant Unicase'},
            {innerText: 'Cormorant Upright', value: 'Cormorant Upright'},
            {innerText: 'Courgette', value: 'Courgette'},
            {innerText: 'Courier Prime', value: 'Courier Prime'},
            {innerText: 'Cousine', value: 'Cousine'},
            {innerText: 'Coustard', value: 'Coustard'},
            {innerText: 'Covered By Your Grace', value: 'Covered By Your Grace'},
            {innerText: 'Crafty Girls', value: 'Crafty Girls'},
            {innerText: 'Creepster', value: 'Creepster'},
            {innerText: 'Crete Round', value: 'Crete Round'},
            {innerText: 'Crimson Pro', value: 'Crimson Pro'},
            {innerText: 'Crimson Text', value: 'Crimson Text'},
            {innerText: 'Croissant One', value: 'Croissant One'},
            {innerText: 'Crushed', value: 'Crushed'},
            {innerText: 'Cuprum', value: 'Cuprum'},
            {innerText: 'Cute Font', value: 'Cute Font'},
            {innerText: 'Cutive', value: 'Cutive'},
            {innerText: 'Cutive Mono', value: 'Cutive Mono'},
            {innerText: 'DM Mono', value: 'DM Mono'},
            {innerText: 'DM Sans', value: 'DM Sans'},
            {innerText: 'DM Serif Display', value: 'DM Serif Display'},
            {innerText: 'DM Serif Text', value: 'DM Serif Text'},
            {innerText: 'Damion', value: 'Damion'},
            {innerText: 'Dancing Script', value: 'Dancing Script'},
            {innerText: 'Dangrek', value: 'Dangrek'},
            {innerText: 'Darker Grotesque', value: 'Darker Grotesque'},
            {innerText: 'David Libre', value: 'David Libre'},
            {innerText: 'Dawning of a New Day', value: 'Dawning of a New Day'},
            {innerText: 'Days One', value: 'Days One'},
            {innerText: 'Dekko', value: 'Dekko'},
            {innerText: 'Dela Gothic One', value: 'Dela Gothic One'},
            {innerText: 'Delius', value: 'Delius'},
            {innerText: 'Delius Swash Caps', value: 'Delius Swash Caps'},
            {innerText: 'Delius Unicase', value: 'Delius Unicase'},
            {innerText: 'Della Respira', value: 'Della Respira'},
            {innerText: 'Denk One', value: 'Denk One'},
            {innerText: 'Devonshire', value: 'Devonshire'},
            {innerText: 'Dhurjati', value: 'Dhurjati'},
            {innerText: 'Didact Gothic', value: 'Didact Gothic'},
            {innerText: 'Diplomata', value: 'Diplomata'},
            {innerText: 'Diplomata SC', value: 'Diplomata SC'},
            {innerText: 'Do Hyeon', value: 'Do Hyeon'},
            {innerText: 'Dokdo', value: 'Dokdo'},
            {innerText: 'Domine', value: 'Domine'},
            {innerText: 'Donegal One', value: 'Donegal One'},
            {innerText: 'Dongle', value: 'Dongle'},
            {innerText: 'Doppio One', value: 'Doppio One'},
            {innerText: 'Dorsa', value: 'Dorsa'},
            {innerText: 'Dosis', value: 'Dosis'},
            {innerText: 'DotGothic16', value: 'DotGothic16'},
            {innerText: 'Dr Sugiyama', value: 'Dr Sugiyama'},
            {innerText: 'Duru Sans', value: 'Duru Sans'},
            {innerText: 'DynaPuff', value: 'DynaPuff'},
            {innerText: 'Dynalight', value: 'Dynalight'},
            {innerText: 'EB Garamond', value: 'EB Garamond'},
            {innerText: 'Eagle Lake', value: 'Eagle Lake'},
            {innerText: 'East Sea Dokdo', value: 'East Sea Dokdo'},
            {innerText: 'Eater', value: 'Eater'},
            {innerText: 'Economica', value: 'Economica'},
            {innerText: 'Eczar', value: 'Eczar'},
            {innerText: 'Edu NSW ACT Foundation', value: 'Edu NSW ACT Foundation'},
            {innerText: 'Edu QLD Beginner', value: 'Edu QLD Beginner'},
            {innerText: 'Edu SA Beginner', value: 'Edu SA Beginner'},
            {innerText: 'Edu TAS Beginner', value: 'Edu TAS Beginner'},
            {innerText: 'Edu VIC WA NT Beginner', value: 'Edu VIC WA NT Beginner'},
            {innerText: 'El Messiri', value: 'El Messiri'},
            {innerText: 'Electrolize', value: 'Electrolize'},
            {innerText: 'Elsie', value: 'Elsie'},
            {innerText: 'Elsie Swash Caps', value: 'Elsie Swash Caps'},
            {innerText: 'Emblema One', value: 'Emblema One'},
            {innerText: 'Emilys Candy', value: 'Emilys Candy'},
            {innerText: 'Encode Sans', value: 'Encode Sans'},
            {innerText: 'Encode Sans Condensed', value: 'Encode Sans Condensed'},
            {innerText: 'Encode Sans Expanded', value: 'Encode Sans Expanded'},
            {innerText: 'Encode Sans SC', value: 'Encode Sans SC'},
            {innerText: 'Encode Sans Semi Condensed', value: 'Encode Sans Semi Condensed'},
            {innerText: 'Encode Sans Semi Expanded', value: 'Encode Sans Semi Expanded'},
            {innerText: 'Engagement', value: 'Engagement'},
            {innerText: 'Englebert', value: 'Englebert'},
            {innerText: 'Enriqueta', value: 'Enriqueta'},
            {innerText: 'Ephesis', value: 'Ephesis'},
            {innerText: 'Epilogue', value: 'Epilogue'},
            {innerText: 'Erica One', value: 'Erica One'},
            {innerText: 'Esteban', value: 'Esteban'},
            {innerText: 'Estonia', value: 'Estonia'},
            {innerText: 'Euphoria Script', value: 'Euphoria Script'},
            {innerText: 'Ewert', value: 'Ewert'},
            {innerText: 'Exo', value: 'Exo'},
            {innerText: 'Exo 2', value: 'Exo 2'},
            {innerText: 'Expletus Sans', value: 'Expletus Sans'},
            {innerText: 'Explora', value: 'Explora'},
            {innerText: 'Fahkwang', value: 'Fahkwang'},
            {innerText: 'Familjen Grotesk', value: 'Familjen Grotesk'},
            {innerText: 'Fanwood Text', value: 'Fanwood Text'},
            {innerText: 'Farro', value: 'Farro'},
            {innerText: 'Farsan', value: 'Farsan'},
            {innerText: 'Fascinate', value: 'Fascinate'},
            {innerText: 'Fascinate Inline', value: 'Fascinate Inline'},
            {innerText: 'Faster One', value: 'Faster One'},
            {innerText: 'Fasthand', value: 'Fasthand'},
            {innerText: 'Fauna One', value: 'Fauna One'},
            {innerText: 'Faustina', value: 'Faustina'},
            {innerText: 'Federant', value: 'Federant'},
            {innerText: 'Federo', value: 'Federo'},
            {innerText: 'Felipa', value: 'Felipa'},
            {innerText: 'Fenix', value: 'Fenix'},
            {innerText: 'Festive', value: 'Festive'},
            {innerText: 'Figtree', value: 'Figtree'},
            {innerText: 'Finger Paint', value: 'Finger Paint'},
            {innerText: 'Finlandica', value: 'Finlandica'},
            {innerText: 'Fira Code', value: 'Fira Code'},
            {innerText: 'Fira Mono', value: 'Fira Mono'},
            {innerText: 'Fira Sans', value: 'Fira Sans'},
            {innerText: 'Fira Sans Condensed', value: 'Fira Sans Condensed'},
            {innerText: 'Fira Sans Extra Condensed', value: 'Fira Sans Extra Condensed'},
            {innerText: 'Fjalla One', value: 'Fjalla One'},
            {innerText: 'Fjord One', value: 'Fjord One'},
            {innerText: 'Flamenco', value: 'Flamenco'},
            {innerText: 'Flavors', value: 'Flavors'},
            {innerText: 'Fleur De Leah', value: 'Fleur De Leah'},
            {innerText: 'Flow Block', value: 'Flow Block'},
            {innerText: 'Flow Circular', value: 'Flow Circular'},
            {innerText: 'Flow Rounded', value: 'Flow Rounded'},
            {innerText: 'Fondamento', value: 'Fondamento'},
            {innerText: 'Fontdiner Swanky', value: 'Fontdiner Swanky'},
            {innerText: 'Forum', value: 'Forum'},
            {innerText: 'Fragment Mono', value: 'Fragment Mono'},
            {innerText: 'Francois One', value: 'Francois One'},
            {innerText: 'Frank Ruhl Libre', value: 'Frank Ruhl Libre'},
            {innerText: 'Fraunces', value: 'Fraunces'},
            {innerText: 'Freckle Face', value: 'Freckle Face'},
            {innerText: 'Fredericka the Great', value: 'Fredericka the Great'},
            {innerText: 'Fredoka', value: 'Fredoka'},
            {innerText: 'Fredoka One', value: 'Fredoka One'},
            {innerText: 'Freehand', value: 'Freehand'},
            {innerText: 'Fresca', value: 'Fresca'},
            {innerText: 'Frijole', value: 'Frijole'},
            {innerText: 'Fruktur', value: 'Fruktur'},
            {innerText: 'Fugaz One', value: 'Fugaz One'},
            {innerText: 'Fuggles', value: 'Fuggles'},
            {innerText: 'Fuzzy Bubbles', value: 'Fuzzy Bubbles'},
            {innerText: 'GFS Didot', value: 'GFS Didot'},
            {innerText: 'GFS Neohellenic', value: 'GFS Neohellenic'},
            {innerText: 'Gabriela', value: 'Gabriela'},
            {innerText: 'Gaegu', value: 'Gaegu'},
            {innerText: 'Gafata', value: 'Gafata'},
            {innerText: 'Galada', value: 'Galada'},
            {innerText: 'Galdeano', value: 'Galdeano'},
            {innerText: 'Galindo', value: 'Galindo'},
            {innerText: 'Gamja Flower', value: 'Gamja Flower'},
            {innerText: 'Gantari', value: 'Gantari'},
            {innerText: 'Gayathri', value: 'Gayathri'},
            {innerText: 'Gelasio', value: 'Gelasio'},
            {innerText: 'Gemunu Libre', value: 'Gemunu Libre'},
            {innerText: 'Genos', value: 'Genos'},
            {innerText: 'Gentium Book Basic', value: 'Gentium Book Basic'},
            {innerText: 'Gentium Book Plus', value: 'Gentium Book Plus'},
            {innerText: 'Gentium Plus', value: 'Gentium Plus'},
            {innerText: 'Geo', value: 'Geo'},
            {innerText: 'Georama', value: 'Georama'},
            {innerText: 'Geostar', value: 'Geostar'},
            {innerText: 'Geostar Fill', value: 'Geostar Fill'},
            {innerText: 'Germania One', value: 'Germania One'},
            {innerText: 'Gideon Roman', value: 'Gideon Roman'},
            {innerText: 'Gidugu', value: 'Gidugu'},
            {innerText: 'Gilda Display', value: 'Gilda Display'},
            {innerText: 'Girassol', value: 'Girassol'},
            {innerText: 'Give You Glory', value: 'Give You Glory'},
            {innerText: 'Glass Antiqua', value: 'Glass Antiqua'},
            {innerText: 'Glegoo', value: 'Glegoo'},
            {innerText: 'Gloria Hallelujah', value: 'Gloria Hallelujah'},
            {innerText: 'Glory', value: 'Glory'},
            {innerText: 'Gluten', value: 'Gluten'},
            {innerText: 'Goblin One', value: 'Goblin One'},
            {innerText: 'Gochi Hand', value: 'Gochi Hand'},
            {innerText: 'Goldman', value: 'Goldman'},
            {innerText: 'Gorditas', value: 'Gorditas'},
            {innerText: 'Gothic A1', value: 'Gothic A1'},
            {innerText: 'Gotu', value: 'Gotu'},
            {innerText: 'Goudy Bookletter 1911', value: 'Goudy Bookletter 1911'},
            {innerText: 'Gowun Batang', value: 'Gowun Batang'},
            {innerText: 'Gowun Dodum', value: 'Gowun Dodum'},
            {innerText: 'Graduate', value: 'Graduate'},
            {innerText: 'Grand Hotel', value: 'Grand Hotel'},
            {innerText: 'Grandstander', value: 'Grandstander'},
            {innerText: 'Grape Nuts', value: 'Grape Nuts'},
            {innerText: 'Gravitas One', value: 'Gravitas One'},
            {innerText: 'Great Vibes', value: 'Great Vibes'},
            {innerText: 'Grechen Fuemen', value: 'Grechen Fuemen'},
            {innerText: 'Grenze', value: 'Grenze'},
            {innerText: 'Grenze Gotisch', value: 'Grenze Gotisch'},
            {innerText: 'Grey Qo', value: 'Grey Qo'},
            {innerText: 'Griffy', value: 'Griffy'},
            {innerText: 'Gruppo', value: 'Gruppo'},
            {innerText: 'Gudea', value: 'Gudea'},
            {innerText: 'Gugi', value: 'Gugi'},
            {innerText: 'Gulzar', value: 'Gulzar'},
            {innerText: 'Gupter', value: 'Gupter'},
            {innerText: 'Gurajada', value: 'Gurajada'},
            {innerText: 'Gwendolyn', value: 'Gwendolyn'},
            {innerText: 'Habibi', value: 'Habibi'},
            {innerText: 'Hachi Maru Pop', value: 'Hachi Maru Pop'},
            {innerText: 'Hahmlet', value: 'Hahmlet'},
            {innerText: 'Halant', value: 'Halant'},
            {innerText: 'Hammersmith One', value: 'Hammersmith One'},
            {innerText: 'Hanalei', value: 'Hanalei'},
            {innerText: 'Hanalei Fill', value: 'Hanalei Fill'},
            {innerText: 'Handlee', value: 'Handlee'},
            {innerText: 'Hanken Grotesk', value: 'Hanken Grotesk'},
            {innerText: 'Hanuman', value: 'Hanuman'},
            {innerText: 'Happy Monkey', value: 'Happy Monkey'},
            {innerText: 'Harmattan', value: 'Harmattan'},
            {innerText: 'Headland One', value: 'Headland One'},
            {innerText: 'Heebo', value: 'Heebo'},
            {innerText: 'Henny Penny', value: 'Henny Penny'},
            {innerText: 'Hepta Slab', value: 'Hepta Slab'},
            {innerText: 'Herr Von Muellerhoff', value: 'Herr Von Muellerhoff'},
            {innerText: 'Hi Melody', value: 'Hi Melody'},
            {innerText: 'Hina Mincho', value: 'Hina Mincho'},
            {innerText: 'Hind', value: 'Hind'},
            {innerText: 'Hind Guntur', value: 'Hind Guntur'},
            {innerText: 'Hind Madurai', value: 'Hind Madurai'},
            {innerText: 'Hind Siliguri', value: 'Hind Siliguri'},
            {innerText: 'Hind Vadodara', value: 'Hind Vadodara'},
            {innerText: 'Holtwood One SC', value: 'Holtwood One SC'},
            {innerText: 'Homemade Apple', value: 'Homemade Apple'},
            {innerText: 'Homenaje', value: 'Homenaje'},
            {innerText: 'Hubballi', value: 'Hubballi'},
            {innerText: 'Hurricane', value: 'Hurricane'},
            {innerText: 'IBM Plex Mono', value: 'IBM Plex Mono'},
            {innerText: 'IBM Plex Sans', value: 'IBM Plex Sans'},
            {innerText: 'IBM Plex Sans Arabic', value: 'IBM Plex Sans Arabic'},
            {innerText: 'IBM Plex Sans Condensed', value: 'IBM Plex Sans Condensed'},
            {innerText: 'IBM Plex Sans Devanagari', value: 'IBM Plex Sans Devanagari'},
            {innerText: 'IBM Plex Sans Hebrew', value: 'IBM Plex Sans Hebrew'},
            {innerText: 'IBM Plex Sans JP', value: 'IBM Plex Sans JP'},
            {innerText: 'IBM Plex Sans KR', value: 'IBM Plex Sans KR'},
            {innerText: 'IBM Plex Sans Thai', value: 'IBM Plex Sans Thai'},
            {innerText: 'IBM Plex Sans Thai Looped', value: 'IBM Plex Sans Thai Looped'},
            {innerText: 'IBM Plex Serif', value: 'IBM Plex Serif'},
            {innerText: 'IM Fell DW Pica', value: 'IM Fell DW Pica'},
            {innerText: 'IM Fell DW Pica SC', value: 'IM Fell DW Pica SC'},
            {innerText: 'IM Fell Double Pica', value: 'IM Fell Double Pica'},
            {innerText: 'IM Fell Double Pica SC', value: 'IM Fell Double Pica SC'},
            {innerText: 'IM Fell English', value: 'IM Fell English'},
            {innerText: 'IM Fell English SC', value: 'IM Fell English SC'},
            {innerText: 'IM Fell French Canon', value: 'IM Fell French Canon'},
            {innerText: 'IM Fell French Canon SC', value: 'IM Fell French Canon SC'},
            {innerText: 'IM Fell Great Primer', value: 'IM Fell Great Primer'},
            {innerText: 'IM Fell Great Primer SC', value: 'IM Fell Great Primer SC'},
            {innerText: 'Ibarra Real Nova', value: 'Ibarra Real Nova'},
            {innerText: 'Iceberg', value: 'Iceberg'},
            {innerText: 'Iceland', value: 'Iceland'},
            {innerText: 'Imbue', value: 'Imbue'},
            {innerText: 'Imperial Script', value: 'Imperial Script'},
            {innerText: 'Imprima', value: 'Imprima'},
            {innerText: 'Inconsolata', value: 'Inconsolata'},
            {innerText: 'Inder', value: 'Inder'},
            {innerText: 'Indie Flower', value: 'Indie Flower'},
            {innerText: 'Ingrid Darling', value: 'Ingrid Darling'},
            {innerText: 'Inika', value: 'Inika'},
            {innerText: 'Inknut Antiqua', value: 'Inknut Antiqua'},
            {innerText: 'Inria Sans', value: 'Inria Sans'},
            {innerText: 'Inria Serif', value: 'Inria Serif'},
            {innerText: 'Inspiration', value: 'Inspiration'},
            {innerText: 'Inter', value: 'Inter'},
            {innerText: 'Inter Tight', value: 'Inter Tight'},
            {innerText: 'Irish Grover', value: 'Irish Grover'},
            {innerText: 'Island Moments', value: 'Island Moments'},
            {innerText: 'Istok Web', value: 'Istok Web'},
            {innerText: 'Italiana', value: 'Italiana'},
            {innerText: 'Italianno', value: 'Italianno'},
            {innerText: 'Itim', value: 'Itim'},
            {innerText: 'Jacques Francois', value: 'Jacques Francois'},
            {innerText: 'Jacques Francois Shadow', value: 'Jacques Francois Shadow'},
            {innerText: 'Jaldi', value: 'Jaldi'},
            {innerText: 'JetBrains Mono', value: 'JetBrains Mono'},
            {innerText: 'Jim Nightshade', value: 'Jim Nightshade'},
            {innerText: 'Joan', value: 'Joan'},
            {innerText: 'Jockey One', value: 'Jockey One'},
            {innerText: 'Jolly Lodger', value: 'Jolly Lodger'},
            {innerText: 'Jomhuria', value: 'Jomhuria'},
            {innerText: 'Jomolhari', value: 'Jomolhari'},
            {innerText: 'Josefin Sans', value: 'Josefin Sans'},
            {innerText: 'Josefin Slab', value: 'Josefin Slab'},
            {innerText: 'Jost', value: 'Jost'},
            {innerText: 'Joti One', value: 'Joti One'},
            {innerText: 'Jua', value: 'Jua'},
            {innerText: 'Judson', value: 'Judson'},
            {innerText: 'Julee', value: 'Julee'},
            {innerText: 'Julius Sans One', value: 'Julius Sans One'},
            {innerText: 'Junge', value: 'Junge'},
            {innerText: 'Jura', value: 'Jura'},
            {innerText: 'Just Another Hand', value: 'Just Another Hand'},
            {innerText: 'Just Me Again Down Here', value: 'Just Me Again Down Here'},
            {innerText: 'K2D', value: 'K2D'},
            {innerText: 'Kadwa', value: 'Kadwa'},
            {innerText: 'Kaisei Decol', value: 'Kaisei Decol'},
            {innerText: 'Kaisei HarunoUmi', value: 'Kaisei HarunoUmi'},
            {innerText: 'Kaisei Opti', value: 'Kaisei Opti'},
            {innerText: 'Kaisei Tokumin', value: 'Kaisei Tokumin'},
            {innerText: 'Kalam', value: 'Kalam'},
            {innerText: 'Kameron', value: 'Kameron'},
            {innerText: 'Kanit', value: 'Kanit'},
            {innerText: 'Kantumruy', value: 'Kantumruy'},
            {innerText: 'Kantumruy Pro', value: 'Kantumruy Pro'},
            {innerText: 'Karantina', value: 'Karantina'},
            {innerText: 'Karla', value: 'Karla'},
            {innerText: 'Karma', value: 'Karma'},
            {innerText: 'Katibeh', value: 'Katibeh'},
            {innerText: 'Kaushan Script', value: 'Kaushan Script'},
            {innerText: 'Kavivanar', value: 'Kavivanar'},
            {innerText: 'Kavoon', value: 'Kavoon'},
            {innerText: 'Kdam Thmor Pro', value: 'Kdam Thmor Pro'},
            {innerText: 'Keania One', value: 'Keania One'},
            {innerText: 'Kelly Slab', value: 'Kelly Slab'},
            {innerText: 'Kenia', value: 'Kenia'},
            {innerText: 'Khand', value: 'Khand'},
            {innerText: 'Khmer', value: 'Khmer'},
            {innerText: 'Khula', value: 'Khula'},
            {innerText: 'Kings', value: 'Kings'},
            {innerText: 'Kirang Haerang', value: 'Kirang Haerang'},
            {innerText: 'Kite One', value: 'Kite One'},
            {innerText: 'Kiwi Maru', value: 'Kiwi Maru'},
            {innerText: 'Klee One', value: 'Klee One'},
            {innerText: 'Knewave', value: 'Knewave'},
            {innerText: 'KoHo', value: 'KoHo'},
            {innerText: 'Kodchasan', value: 'Kodchasan'},
            {innerText: 'Koh Santepheap', value: 'Koh Santepheap'},
            {innerText: 'Kolker Brush', value: 'Kolker Brush'},
            {innerText: 'Kosugi', value: 'Kosugi'},
            {innerText: 'Kosugi Maru', value: 'Kosugi Maru'},
            {innerText: 'Kotta One', value: 'Kotta One'},
            {innerText: 'Koulen', value: 'Koulen'},
            {innerText: 'Kranky', value: 'Kranky'},
            {innerText: 'Kreon', value: 'Kreon'},
            {innerText: 'Kristi', value: 'Kristi'},
            {innerText: 'Krona One', value: 'Krona One'},
            {innerText: 'Krub', value: 'Krub'},
            {innerText: 'Kufam', value: 'Kufam'},
            {innerText: 'Kulim Park', value: 'Kulim Park'},
            {innerText: 'Kumar One', value: 'Kumar One'},
            {innerText: 'Kumar One Outline', value: 'Kumar One Outline'},
            {innerText: 'Kumbh Sans', value: 'Kumbh Sans'},
            {innerText: 'Kurale', value: 'Kurale'},
            {innerText: 'La Belle Aurore', value: 'La Belle Aurore'},
            {innerText: 'Lacquer', value: 'Lacquer'},
            {innerText: 'Laila', value: 'Laila'},
            {innerText: 'Lakki Reddy', value: 'Lakki Reddy'},
            {innerText: 'Lalezar', value: 'Lalezar'},
            {innerText: 'Lancelot', value: 'Lancelot'},
            {innerText: 'Langar', value: 'Langar'},
            {innerText: 'Lateef', value: 'Lateef'},
            {innerText: 'Lato', value: 'Lato'},
            {innerText: 'Lavishly Yours', value: 'Lavishly Yours'},
            {innerText: 'League Gothic', value: 'League Gothic'},
            {innerText: 'League Script', value: 'League Script'},
            {innerText: 'League Spartan', value: 'League Spartan'},
            {innerText: 'Leckerli One', value: 'Leckerli One'},
            {innerText: 'Ledger', value: 'Ledger'},
            {innerText: 'Lekton', value: 'Lekton'},
            {innerText: 'Lemon', value: 'Lemon'},
            {innerText: 'Lemonada', value: 'Lemonada'},
            {innerText: 'Lexend', value: 'Lexend'},
            {innerText: 'Lexend Deca', value: 'Lexend Deca'},
            {innerText: 'Lexend Exa', value: 'Lexend Exa'},
            {innerText: 'Lexend Giga', value: 'Lexend Giga'},
            {innerText: 'Lexend Mega', value: 'Lexend Mega'},
            {innerText: 'Lexend Peta', value: 'Lexend Peta'},
            {innerText: 'Lexend Tera', value: 'Lexend Tera'},
            {innerText: 'Lexend Zetta', value: 'Lexend Zetta'},
            {innerText: 'Libre Barcode 128', value: 'Libre Barcode 128'},
            {innerText: 'Libre Barcode 128 Text', value: 'Libre Barcode 128 Text'},
            {innerText: 'Libre Barcode 39', value: 'Libre Barcode 39'},
            {innerText: 'Libre Barcode 39 Extended', value: 'Libre Barcode 39 Extended'},
            {innerText: 'Libre Barcode 39 Extended Text', value: 'Libre Barcode 39 Extended Text'},
            {innerText: 'Libre Barcode 39 Text', value: 'Libre Barcode 39 Text'},
            {innerText: 'Libre Barcode EAN13 Text', value: 'Libre Barcode EAN13 Text'},
            {innerText: 'Libre Baskerville', value: 'Libre Baskerville'},
            {innerText: 'Libre Bodoni', value: 'Libre Bodoni'},
            {innerText: 'Libre Caslon Display', value: 'Libre Caslon Display'},
            {innerText: 'Libre Caslon Text', value: 'Libre Caslon Text'},
            {innerText: 'Libre Franklin', value: 'Libre Franklin'},
            {innerText: 'Licorice', value: 'Licorice'},
            {innerText: 'Life Savers', value: 'Life Savers'},
            {innerText: 'Lilita One', value: 'Lilita One'},
            {innerText: 'Lily Script One', value: 'Lily Script One'},
            {innerText: 'Limelight', value: 'Limelight'},
            {innerText: 'Linden Hill', value: 'Linden Hill'},
            {innerText: 'Literata', value: 'Literata'},
            {innerText: 'Liu Jian Mao Cao', value: 'Liu Jian Mao Cao'},
            {innerText: 'Livvic', value: 'Livvic'},
            {innerText: 'Lobster', value: 'Lobster'},
            {innerText: 'Lobster Two', value: 'Lobster Two'},
            {innerText: 'Londrina Outline', value: 'Londrina Outline'},
            {innerText: 'Londrina Shadow', value: 'Londrina Shadow'},
            {innerText: 'Londrina Sketch', value: 'Londrina Sketch'},
            {innerText: 'Londrina Solid', value: 'Londrina Solid'},
            {innerText: 'Long Cang', value: 'Long Cang'},
            {innerText: 'Lora', value: 'Lora'},
            {innerText: 'Love Light', value: 'Love Light'},
            {innerText: 'Love Ya Like A Sister', value: 'Love Ya Like A Sister'},
            {innerText: 'Loved by the King', value: 'Loved by the King'},
            {innerText: 'Lovers Quarrel', value: 'Lovers Quarrel'},
            {innerText: 'Luckiest Guy', value: 'Luckiest Guy'},
            {innerText: 'Lusitana', value: 'Lusitana'},
            {innerText: 'Lustria', value: 'Lustria'},
            {innerText: 'Luxurious Roman', value: 'Luxurious Roman'},
            {innerText: 'Luxurious Script', value: 'Luxurious Script'},
            {innerText: 'M PLUS 1', value: 'M PLUS 1'},
            {innerText: 'M PLUS 1 Code', value: 'M PLUS 1 Code'},
            {innerText: 'M PLUS 1p', value: 'M PLUS 1p'},
            {innerText: 'M PLUS 2', value: 'M PLUS 2'},
            {innerText: 'M PLUS Code Latin', value: 'M PLUS Code Latin'},
            {innerText: 'M PLUS Rounded 1c', value: 'M PLUS Rounded 1c'},
            {innerText: 'Ma Shan Zheng', value: 'Ma Shan Zheng'},
            {innerText: 'Macondo', value: 'Macondo'},
            {innerText: 'Macondo Swash Caps', value: 'Macondo Swash Caps'},
            {innerText: 'Mada', value: 'Mada'},
            {innerText: 'Magra', value: 'Magra'},
            {innerText: 'Maiden Orange', value: 'Maiden Orange'},
            {innerText: 'Maitree', value: 'Maitree'},
            {innerText: 'Major Mono Display', value: 'Major Mono Display'},
            {innerText: 'Mako', value: 'Mako'},
            {innerText: 'Mali', value: 'Mali'},
            {innerText: 'Mallanna', value: 'Mallanna'},
            {innerText: 'Mandali', value: 'Mandali'},
            {innerText: 'Manjari', value: 'Manjari'},
            {innerText: 'Manrope', value: 'Manrope'},
            {innerText: 'Mansalva', value: 'Mansalva'},
            {innerText: 'Manuale', value: 'Manuale'},
            {innerText: 'Marcellus', value: 'Marcellus'},
            {innerText: 'Marcellus SC', value: 'Marcellus SC'},
            {innerText: 'Marck Script', value: 'Marck Script'},
            {innerText: 'Margarine', value: 'Margarine'},
            {innerText: 'Marhey', value: 'Marhey'},
            {innerText: 'Markazi Text', value: 'Markazi Text'},
            {innerText: 'Marko One', value: 'Marko One'},
            {innerText: 'Marmelad', value: 'Marmelad'},
            {innerText: 'Martel', value: 'Martel'},
            {innerText: 'Martel Sans', value: 'Martel Sans'},
            {innerText: 'Martian Mono', value: 'Martian Mono'},
            {innerText: 'Marvel', value: 'Marvel'},
            {innerText: 'Mate', value: 'Mate'},
            {innerText: 'Mate SC', value: 'Mate SC'},
            {innerText: 'Maven Pro', value: 'Maven Pro'},
            {innerText: 'McLaren', value: 'McLaren'},
            {innerText: 'Mea Culpa', value: 'Mea Culpa'},
            {innerText: 'Meddon', value: 'Meddon'},
            {innerText: 'MedievalSharp', value: 'MedievalSharp'},
            {innerText: 'Medula One', value: 'Medula One'},
            {innerText: 'Meera Inimai', value: 'Meera Inimai'},
            {innerText: 'Megrim', value: 'Megrim'},
            {innerText: 'Meie Script', value: 'Meie Script'},
            {innerText: 'Meow Script', value: 'Meow Script'},
            {innerText: 'Merienda', value: 'Merienda'},
            {innerText: 'Merienda One', value: 'Merienda One'},
            {innerText: 'Merriweather', value: 'Merriweather'},
            {innerText: 'Merriweather Sans', value: 'Merriweather Sans'},
            {innerText: 'Metal', value: 'Metal'},
            {innerText: 'Metal Mania', value: 'Metal Mania'},
            {innerText: 'Metamorphous', value: 'Metamorphous'},
            {innerText: 'Metrophobic', value: 'Metrophobic'},
            {innerText: 'Michroma', value: 'Michroma'},
            {innerText: 'Milonga', value: 'Milonga'},
            {innerText: 'Miltonian', value: 'Miltonian'},
            {innerText: 'Miltonian Tattoo', value: 'Miltonian Tattoo'},
            {innerText: 'Mina', value: 'Mina'},
            {innerText: 'Mingzat', value: 'Mingzat'},
            {innerText: 'Miniver', value: 'Miniver'},
            {innerText: 'Miriam Libre', value: 'Miriam Libre'},
            {innerText: 'Mirza', value: 'Mirza'},
            {innerText: 'Miss Fajardose', value: 'Miss Fajardose'},
            {innerText: 'Mitr', value: 'Mitr'},
            {innerText: 'Mochiy Pop One', value: 'Mochiy Pop One'},
            {innerText: 'Mochiy Pop P One', value: 'Mochiy Pop P One'},
            {innerText: 'Modak', value: 'Modak'},
            {innerText: 'Modern Antiqua', value: 'Modern Antiqua'},
            {innerText: 'Mogra', value: 'Mogra'},
            {innerText: 'Mohave', value: 'Mohave'},
            {innerText: 'Molengo', value: 'Molengo'},
            {innerText: 'Molle', value: 'Molle'},
            {innerText: 'Monda', value: 'Monda'},
            {innerText: 'Monofett', value: 'Monofett'},
            {innerText: 'Monoton', value: 'Monoton'},
            {innerText: 'Monsieur La Doulaise', value: 'Monsieur La Doulaise'},
            {innerText: 'Montaga', value: 'Montaga'},
            {innerText: 'Montagu Slab', value: 'Montagu Slab'},
            {innerText: 'MonteCarlo', value: 'MonteCarlo'},
            {innerText: 'Montez', value: 'Montez'},
            {innerText: 'Montserrat', value: 'Montserrat'},
            {innerText: 'Montserrat Alternates', value: 'Montserrat Alternates'},
            {innerText: 'Montserrat Subrayada', value: 'Montserrat Subrayada'},
            {innerText: 'Moo Lah Lah', value: 'Moo Lah Lah'},
            {innerText: 'Moon Dance', value: 'Moon Dance'},
            {innerText: 'Moul', value: 'Moul'},
            {innerText: 'Moulpali', value: 'Moulpali'},
            {innerText: 'Mountains of Christmas', value: 'Mountains of Christmas'},
            {innerText: 'Mouse Memoirs', value: 'Mouse Memoirs'},
            {innerText: 'Mr Bedfort', value: 'Mr Bedfort'},
            {innerText: 'Mr Dafoe', value: 'Mr Dafoe'},
            {innerText: 'Mr De Haviland', value: 'Mr De Haviland'},
            {innerText: 'Mrs Saint Delafield', value: 'Mrs Saint Delafield'},
            {innerText: 'Mrs Sheppards', value: 'Mrs Sheppards'},
            {innerText: 'Ms Madi', value: 'Ms Madi'},
            {innerText: 'Mukta', value: 'Mukta'},
            {innerText: 'Mukta Mahee', value: 'Mukta Mahee'},
            {innerText: 'Mukta Malar', value: 'Mukta Malar'},
            {innerText: 'Mukta Vaani', value: 'Mukta Vaani'},
            {innerText: 'Mulish', value: 'Mulish'},
            {innerText: 'Murecho', value: 'Murecho'},
            {innerText: 'MuseoModerno', value: 'MuseoModerno'},
            {innerText: 'My Soul', value: 'My Soul'},
            {innerText: 'Mystery Quest', value: 'Mystery Quest'},
            {innerText: 'NTR', value: 'NTR'},
            {innerText: 'Nabla', value: 'Nabla'},
            {innerText: 'Nanum Brush Script', value: 'Nanum Brush Script'},
            {innerText: 'Nanum Gothic', value: 'Nanum Gothic'},
            {innerText: 'Nanum Gothic Coding', value: 'Nanum Gothic Coding'},
            {innerText: 'Nanum Myeongjo', value: 'Nanum Myeongjo'},
            {innerText: 'Nanum Pen Script', value: 'Nanum Pen Script'},
            {innerText: 'Neonderthaw', value: 'Neonderthaw'},
            {innerText: 'Nerko One', value: 'Nerko One'},
            {innerText: 'Neucha', value: 'Neucha'},
            {innerText: 'Neuton', value: 'Neuton'},
            {innerText: 'New Rocker', value: 'New Rocker'},
            {innerText: 'New Tegomin', value: 'New Tegomin'},
            {innerText: 'News Cycle', value: 'News Cycle'},
            {innerText: 'Newsreader', value: 'Newsreader'},
            {innerText: 'Niconne', value: 'Niconne'},
            {innerText: 'Niramit', value: 'Niramit'},
            {innerText: 'Nixie One', value: 'Nixie One'},
            {innerText: 'Nobile', value: 'Nobile'},
            {innerText: 'Nokora', value: 'Nokora'},
            {innerText: 'Norican', value: 'Norican'},
            {innerText: 'Nosifer', value: 'Nosifer'},
            {innerText: 'Notable', value: 'Notable'},
            {innerText: 'Nothing You Could Do', value: 'Nothing You Could Do'},
            {innerText: 'Noticia Text', value: 'Noticia Text'},
            {innerText: 'Noto Color Emoji', value: 'Noto Color Emoji'},
            {innerText: 'Noto Emoji', value: 'Noto Emoji'},
            {innerText: 'Noto Music', value: 'Noto Music'},
            {innerText: 'Noto Nastaliq Urdu', value: 'Noto Nastaliq Urdu'},
            {innerText: 'Noto Rashi Hebrew', value: 'Noto Rashi Hebrew'},
            {innerText: 'Noto Sans', value: 'Noto Sans'},
            {innerText: 'Noto Sans Adlam', value: 'Noto Sans Adlam'},
            {innerText: 'Noto Sans Adlam Unjoined', value: 'Noto Sans Adlam Unjoined'},
            {innerText: 'Noto Sans Anatolian Hieroglyphs', value: 'Noto Sans Anatolian Hieroglyphs'},
            {innerText: 'Noto Sans Arabic', value: 'Noto Sans Arabic'},
            {innerText: 'Noto Sans Armenian', value: 'Noto Sans Armenian'},
            {innerText: 'Noto Sans Avestan', value: 'Noto Sans Avestan'},
            {innerText: 'Noto Sans Balinese', value: 'Noto Sans Balinese'},
            {innerText: 'Noto Sans Bamum', value: 'Noto Sans Bamum'},
            {innerText: 'Noto Sans Bassa Vah', value: 'Noto Sans Bassa Vah'},
            {innerText: 'Noto Sans Batak', value: 'Noto Sans Batak'},
            {innerText: 'Noto Sans Bengali', value: 'Noto Sans Bengali'},
            {innerText: 'Noto Sans Bhaiksuki', value: 'Noto Sans Bhaiksuki'},
            {innerText: 'Noto Sans Brahmi', value: 'Noto Sans Brahmi'},
            {innerText: 'Noto Sans Buginese', value: 'Noto Sans Buginese'},
            {innerText: 'Noto Sans Buhid', value: 'Noto Sans Buhid'},
            {innerText: 'Noto Sans Canadian Aboriginal', value: 'Noto Sans Canadian Aboriginal'},
            {innerText: 'Noto Sans Carian', value: 'Noto Sans Carian'},
            {innerText: 'Noto Sans Caucasian Albanian', value: 'Noto Sans Caucasian Albanian'},
            {innerText: 'Noto Sans Chakma', value: 'Noto Sans Chakma'},
            {innerText: 'Noto Sans Cham', value: 'Noto Sans Cham'},
            {innerText: 'Noto Sans Cherokee', value: 'Noto Sans Cherokee'},
            {innerText: 'Noto Sans Coptic', value: 'Noto Sans Coptic'},
            {innerText: 'Noto Sans Cuneiform', value: 'Noto Sans Cuneiform'},
            {innerText: 'Noto Sans Cypriot', value: 'Noto Sans Cypriot'},
            {innerText: 'Noto Sans Deseret', value: 'Noto Sans Deseret'},
            {innerText: 'Noto Sans Devanagari', value: 'Noto Sans Devanagari'},
            {innerText: 'Noto Sans Display', value: 'Noto Sans Display'},
            {innerText: 'Noto Sans Duployan', value: 'Noto Sans Duployan'},
            {innerText: 'Noto Sans Egyptian Hieroglyphs', value: 'Noto Sans Egyptian Hieroglyphs'},
            {innerText: 'Noto Sans Elbasan', value: 'Noto Sans Elbasan'},
            {innerText: 'Noto Sans Elymaic', value: 'Noto Sans Elymaic'},
            {innerText: 'Noto Sans Ethiopic', value: 'Noto Sans Ethiopic'},
            {innerText: 'Noto Sans Georgian', value: 'Noto Sans Georgian'},
            {innerText: 'Noto Sans Glagolitic', value: 'Noto Sans Glagolitic'},
            {innerText: 'Noto Sans Gothic', value: 'Noto Sans Gothic'},
            {innerText: 'Noto Sans Grantha', value: 'Noto Sans Grantha'},
            {innerText: 'Noto Sans Gujarati', value: 'Noto Sans Gujarati'},
            {innerText: 'Noto Sans Gunjala Gondi', value: 'Noto Sans Gunjala Gondi'},
            {innerText: 'Noto Sans Gurmukhi', value: 'Noto Sans Gurmukhi'},
            {innerText: 'Noto Sans HK', value: 'Noto Sans HK'},
            {innerText: 'Noto Sans Hanifi Rohingya', value: 'Noto Sans Hanifi Rohingya'},
            {innerText: 'Noto Sans Hanunoo', value: 'Noto Sans Hanunoo'},
            {innerText: 'Noto Sans Hatran', value: 'Noto Sans Hatran'},
            {innerText: 'Noto Sans Imperial Aramaic', value: 'Noto Sans Imperial Aramaic'},
            {innerText: 'Noto Sans Indic Siyaq Numbers', value: 'Noto Sans Indic Siyaq Numbers'},
            {innerText: 'Noto Sans Inscriptional Pahlavi', value: 'Noto Sans Inscriptional Pahlavi'},
            {innerText: 'Noto Sans Inscriptional Parthian', value: 'Noto Sans Inscriptional Parthian'},
            {innerText: 'Noto Sans JP', value: 'Noto Sans JP'},
            {innerText: 'Noto Sans Javanese', value: 'Noto Sans Javanese'},
            {innerText: 'Noto Sans KR', value: 'Noto Sans KR'},
            {innerText: 'Noto Sans Kaithi', value: 'Noto Sans Kaithi'},
            {innerText: 'Noto Sans Kannada', value: 'Noto Sans Kannada'},
            {innerText: 'Noto Sans Kayah Li', value: 'Noto Sans Kayah Li'},
            {innerText: 'Noto Sans Kharoshthi', value: 'Noto Sans Kharoshthi'},
            {innerText: 'Noto Sans Khmer', value: 'Noto Sans Khmer'},
            {innerText: 'Noto Sans Khojki', value: 'Noto Sans Khojki'},
            {innerText: 'Noto Sans Khudawadi', value: 'Noto Sans Khudawadi'},
            {innerText: 'Noto Sans Lao', value: 'Noto Sans Lao'},
            {innerText: 'Noto Sans Lao Looped', value: 'Noto Sans Lao Looped'},
            {innerText: 'Noto Sans Lepcha', value: 'Noto Sans Lepcha'},
            {innerText: 'Noto Sans Limbu', value: 'Noto Sans Limbu'},
            {innerText: 'Noto Sans Linear A', value: 'Noto Sans Linear A'},
            {innerText: 'Noto Sans Linear B', value: 'Noto Sans Linear B'},
            {innerText: 'Noto Sans Lisu', value: 'Noto Sans Lisu'},
            {innerText: 'Noto Sans Lycian', value: 'Noto Sans Lycian'},
            {innerText: 'Noto Sans Lydian', value: 'Noto Sans Lydian'},
            {innerText: 'Noto Sans Mahajani', value: 'Noto Sans Mahajani'},
            {innerText: 'Noto Sans Malayalam', value: 'Noto Sans Malayalam'},
            {innerText: 'Noto Sans Mandaic', value: 'Noto Sans Mandaic'},
            {innerText: 'Noto Sans Manichaean', value: 'Noto Sans Manichaean'},
            {innerText: 'Noto Sans Marchen', value: 'Noto Sans Marchen'},
            {innerText: 'Noto Sans Masaram Gondi', value: 'Noto Sans Masaram Gondi'},
            {innerText: 'Noto Sans Math', value: 'Noto Sans Math'},
            {innerText: 'Noto Sans Mayan Numerals', value: 'Noto Sans Mayan Numerals'},
            {innerText: 'Noto Sans Medefaidrin', value: 'Noto Sans Medefaidrin'},
            {innerText: 'Noto Sans Meetei Mayek', value: 'Noto Sans Meetei Mayek'},
            {innerText: 'Noto Sans Mende Kikakui', value: 'Noto Sans Mende Kikakui'},
            {innerText: 'Noto Sans Meroitic', value: 'Noto Sans Meroitic'},
            {innerText: 'Noto Sans Miao', value: 'Noto Sans Miao'},
            {innerText: 'Noto Sans Modi', value: 'Noto Sans Modi'},
            {innerText: 'Noto Sans Mongolian', value: 'Noto Sans Mongolian'},
            {innerText: 'Noto Sans Mono', value: 'Noto Sans Mono'},
            {innerText: 'Noto Sans Mro', value: 'Noto Sans Mro'},
            {innerText: 'Noto Sans Multani', value: 'Noto Sans Multani'},
            {innerText: 'Noto Sans Myanmar', value: 'Noto Sans Myanmar'},
            {innerText: 'Noto Sans N Ko', value: 'Noto Sans N Ko'},
            {innerText: 'Noto Sans Nabataean', value: 'Noto Sans Nabataean'},
            {innerText: 'Noto Sans New Tai Lue', value: 'Noto Sans New Tai Lue'},
            {innerText: 'Noto Sans Newa', value: 'Noto Sans Newa'},
            {innerText: 'Noto Sans Nushu', value: 'Noto Sans Nushu'},
            {innerText: 'Noto Sans Ogham', value: 'Noto Sans Ogham'},
            {innerText: 'Noto Sans Ol Chiki', value: 'Noto Sans Ol Chiki'},
            {innerText: 'Noto Sans Old Hungarian', value: 'Noto Sans Old Hungarian'},
            {innerText: 'Noto Sans Old Italic', value: 'Noto Sans Old Italic'},
            {innerText: 'Noto Sans Old North Arabian', value: 'Noto Sans Old North Arabian'},
            {innerText: 'Noto Sans Old Permic', value: 'Noto Sans Old Permic'},
            {innerText: 'Noto Sans Old Persian', value: 'Noto Sans Old Persian'},
            {innerText: 'Noto Sans Old Sogdian', value: 'Noto Sans Old Sogdian'},
            {innerText: 'Noto Sans Old South Arabian', value: 'Noto Sans Old South Arabian'},
            {innerText: 'Noto Sans Old Turkic', value: 'Noto Sans Old Turkic'},
            {innerText: 'Noto Sans Oriya', value: 'Noto Sans Oriya'},
            {innerText: 'Noto Sans Osage', value: 'Noto Sans Osage'},
            {innerText: 'Noto Sans Osmanya', value: 'Noto Sans Osmanya'},
            {innerText: 'Noto Sans Pahawh Hmong', value: 'Noto Sans Pahawh Hmong'},
            {innerText: 'Noto Sans Palmyrene', value: 'Noto Sans Palmyrene'},
            {innerText: 'Noto Sans Pau Cin Hau', value: 'Noto Sans Pau Cin Hau'},
            {innerText: 'Noto Sans Phags Pa', value: 'Noto Sans Phags Pa'},
            {innerText: 'Noto Sans Phoenician', value: 'Noto Sans Phoenician'},
            {innerText: 'Noto Sans Psalter Pahlavi', value: 'Noto Sans Psalter Pahlavi'},
            {innerText: 'Noto Sans Rejang', value: 'Noto Sans Rejang'},
            {innerText: 'Noto Sans Runic', value: 'Noto Sans Runic'},
            {innerText: 'Noto Sans SC', value: 'Noto Sans SC'},
            {innerText: 'Noto Sans Samaritan', value: 'Noto Sans Samaritan'},
            {innerText: 'Noto Sans Saurashtra', value: 'Noto Sans Saurashtra'},
            {innerText: 'Noto Sans Sharada', value: 'Noto Sans Sharada'},
            {innerText: 'Noto Sans Shavian', value: 'Noto Sans Shavian'},
            {innerText: 'Noto Sans Siddham', value: 'Noto Sans Siddham'},
            {innerText: 'Noto Sans SignWriting', value: 'Noto Sans SignWriting'},
            {innerText: 'Noto Sans Sinhala', value: 'Noto Sans Sinhala'},
            {innerText: 'Noto Sans Sogdian', value: 'Noto Sans Sogdian'},
            {innerText: 'Noto Sans Sora Sompeng', value: 'Noto Sans Sora Sompeng'},
            {innerText: 'Noto Sans Soyombo', value: 'Noto Sans Soyombo'},
            {innerText: 'Noto Sans Sundanese', value: 'Noto Sans Sundanese'},
            {innerText: 'Noto Sans Syloti Nagri', value: 'Noto Sans Syloti Nagri'},
            {innerText: 'Noto Sans Symbols', value: 'Noto Sans Symbols'},
            {innerText: 'Noto Sans Symbols 2', value: 'Noto Sans Symbols 2'},
            {innerText: 'Noto Sans Syriac', value: 'Noto Sans Syriac'},
            {innerText: 'Noto Sans TC', value: 'Noto Sans TC'},
            {innerText: 'Noto Sans Tagalog', value: 'Noto Sans Tagalog'},
            {innerText: 'Noto Sans Tagbanwa', value: 'Noto Sans Tagbanwa'},
            {innerText: 'Noto Sans Tai Le', value: 'Noto Sans Tai Le'},
            {innerText: 'Noto Sans Tai Tham', value: 'Noto Sans Tai Tham'},
            {innerText: 'Noto Sans Tai Viet', value: 'Noto Sans Tai Viet'},
            {innerText: 'Noto Sans Takri', value: 'Noto Sans Takri'},
            {innerText: 'Noto Sans Tamil', value: 'Noto Sans Tamil'},
            {innerText: 'Noto Sans Tamil Supplement', value: 'Noto Sans Tamil Supplement'},
            {innerText: 'Noto Sans Tangsa', value: 'Noto Sans Tangsa'},
            {innerText: 'Noto Sans Telugu', value: 'Noto Sans Telugu'},
            {innerText: 'Noto Sans Thaana', value: 'Noto Sans Thaana'},
            {innerText: 'Noto Sans Thai', value: 'Noto Sans Thai'},
            {innerText: 'Noto Sans Thai Looped', value: 'Noto Sans Thai Looped'},
            {innerText: 'Noto Sans Tifinagh', value: 'Noto Sans Tifinagh'},
            {innerText: 'Noto Sans Tirhuta', value: 'Noto Sans Tirhuta'},
            {innerText: 'Noto Sans Ugaritic', value: 'Noto Sans Ugaritic'},
            {innerText: 'Noto Sans Vai', value: 'Noto Sans Vai'},
            {innerText: 'Noto Sans Wancho', value: 'Noto Sans Wancho'},
            {innerText: 'Noto Sans Warang Citi', value: 'Noto Sans Warang Citi'},
            {innerText: 'Noto Sans Yi', value: 'Noto Sans Yi'},
            {innerText: 'Noto Sans Zanabazar Square', value: 'Noto Sans Zanabazar Square'},
            {innerText: 'Noto Serif', value: 'Noto Serif'},
            {innerText: 'Noto Serif Ahom', value: 'Noto Serif Ahom'},
            {innerText: 'Noto Serif Armenian', value: 'Noto Serif Armenian'},
            {innerText: 'Noto Serif Balinese', value: 'Noto Serif Balinese'},
            {innerText: 'Noto Serif Bengali', value: 'Noto Serif Bengali'},
            {innerText: 'Noto Serif Devanagari', value: 'Noto Serif Devanagari'},
            {innerText: 'Noto Serif Display', value: 'Noto Serif Display'},
            {innerText: 'Noto Serif Dogra', value: 'Noto Serif Dogra'},
            {innerText: 'Noto Serif Ethiopic', value: 'Noto Serif Ethiopic'},
            {innerText: 'Noto Serif Georgian', value: 'Noto Serif Georgian'},
            {innerText: 'Noto Serif Grantha', value: 'Noto Serif Grantha'},
            {innerText: 'Noto Serif Gujarati', value: 'Noto Serif Gujarati'},
            {innerText: 'Noto Serif Gurmukhi', value: 'Noto Serif Gurmukhi'},
            {innerText: 'Noto Serif HK', value: 'Noto Serif HK'},
            {innerText: 'Noto Serif Hebrew', value: 'Noto Serif Hebrew'},
            {innerText: 'Noto Serif JP', value: 'Noto Serif JP'},
            {innerText: 'Noto Serif KR', value: 'Noto Serif KR'},
            {innerText: 'Noto Serif Kannada', value: 'Noto Serif Kannada'},
            {innerText: 'Noto Serif Khmer', value: 'Noto Serif Khmer'},
            {innerText: 'Noto Serif Khojki', value: 'Noto Serif Khojki'},
            {innerText: 'Noto Serif Lao', value: 'Noto Serif Lao'},
            {innerText: 'Noto Serif Malayalam', value: 'Noto Serif Malayalam'},
            {innerText: 'Noto Serif Myanmar', value: 'Noto Serif Myanmar'},
            {innerText: 'Noto Serif NP Hmong', value: 'Noto Serif NP Hmong'},
            {innerText: 'Noto Serif Nyiakeng Puachue Hmong', value: 'Noto Serif Nyiakeng Puachue Hmong'},
            {innerText: 'Noto Serif Oriya', value: 'Noto Serif Oriya'},
            {innerText: 'Noto Serif SC', value: 'Noto Serif SC'},
            {innerText: 'Noto Serif Sinhala', value: 'Noto Serif Sinhala'},
            {innerText: 'Noto Serif TC', value: 'Noto Serif TC'},
            {innerText: 'Noto Serif Tamil', value: 'Noto Serif Tamil'},
            {innerText: 'Noto Serif Tangut', value: 'Noto Serif Tangut'},
            {innerText: 'Noto Serif Telugu', value: 'Noto Serif Telugu'},
            {innerText: 'Noto Serif Thai', value: 'Noto Serif Thai'},
            {innerText: 'Noto Serif Tibetan', value: 'Noto Serif Tibetan'},
            {innerText: 'Noto Serif Toto', value: 'Noto Serif Toto'},
            {innerText: 'Noto Serif Yezidi', value: 'Noto Serif Yezidi'},
            {innerText: 'Noto Traditional Nushu', value: 'Noto Traditional Nushu'},
            {innerText: 'Nova Cut', value: 'Nova Cut'},
            {innerText: 'Nova Flat', value: 'Nova Flat'},
            {innerText: 'Nova Mono', value: 'Nova Mono'},
            {innerText: 'Nova Oval', value: 'Nova Oval'},
            {innerText: 'Nova Round', value: 'Nova Round'},
            {innerText: 'Nova Script', value: 'Nova Script'},
            {innerText: 'Nova Slim', value: 'Nova Slim'},
            {innerText: 'Nova Square', value: 'Nova Square'},
            {innerText: 'Numans', value: 'Numans'},
            {innerText: 'Nunito', value: 'Nunito'},
            {innerText: 'Nunito Sans', value: 'Nunito Sans'},
            {innerText: 'Nuosu SIL', value: 'Nuosu SIL'},
            {innerText: 'Odibee Sans', value: 'Odibee Sans'},
            {innerText: 'Odor Mean Chey', value: 'Odor Mean Chey'},
            {innerText: 'Offside', value: 'Offside'},
            {innerText: 'Oi', value: 'Oi'},
            {innerText: 'Old Standard TT', value: 'Old Standard TT'},
            {innerText: 'Oldenburg', value: 'Oldenburg'},
            {innerText: 'Ole', value: 'Ole'},
            {innerText: 'Oleo Script', value: 'Oleo Script'},
            {innerText: 'Oleo Script Swash Caps', value: 'Oleo Script Swash Caps'},
            {innerText: 'Oooh Baby', value: 'Oooh Baby'},
            {innerText: 'Open Sans', value: 'Open Sans'},
            {innerText: 'Oranienbaum', value: 'Oranienbaum'},
            {innerText: 'Orbitron', value: 'Orbitron'},
            {innerText: 'Oregano', value: 'Oregano'},
            {innerText: 'Orelega One', value: 'Orelega One'},
            {innerText: 'Orienta', value: 'Orienta'},
            {innerText: 'Original Surfer', value: 'Original Surfer'},
            {innerText: 'Oswald', value: 'Oswald'},
            {innerText: 'Outfit', value: 'Outfit'},
            {innerText: 'Over the Rainbow', value: 'Over the Rainbow'},
            {innerText: 'Overlock', value: 'Overlock'},
            {innerText: 'Overlock SC', value: 'Overlock SC'},
            {innerText: 'Overpass', value: 'Overpass'},
            {innerText: 'Overpass Mono', value: 'Overpass Mono'},
            {innerText: 'Ovo', value: 'Ovo'},
            {innerText: 'Oxanium', value: 'Oxanium'},
            {innerText: 'Oxygen', value: 'Oxygen'},
            {innerText: 'Oxygen Mono', value: 'Oxygen Mono'},
            {innerText: 'PT Mono', value: 'PT Mono'},
            {innerText: 'PT Sans', value: 'PT Sans'},
            {innerText: 'PT Sans Caption', value: 'PT Sans Caption'},
            {innerText: 'PT Sans Narrow', value: 'PT Sans Narrow'},
            {innerText: 'PT Serif', value: 'PT Serif'},
            {innerText: 'PT Serif Caption', value: 'PT Serif Caption'},
            {innerText: 'Pacifico', value: 'Pacifico'},
            {innerText: 'Padauk', value: 'Padauk'},
            {innerText: 'Padyakke Expanded One', value: 'Padyakke Expanded One'},
            {innerText: 'Palanquin', value: 'Palanquin'},
            {innerText: 'Palanquin Dark', value: 'Palanquin Dark'},
            {innerText: 'Pangolin', value: 'Pangolin'},
            {innerText: 'Paprika', value: 'Paprika'},
            {innerText: 'Parisienne', value: 'Parisienne'},
            {innerText: 'Passero One', value: 'Passero One'},
            {innerText: 'Passion One', value: 'Passion One'},
            {innerText: 'Passions Conflict', value: 'Passions Conflict'},
            {innerText: 'Pathway Gothic One', value: 'Pathway Gothic One'},
            {innerText: 'Patrick Hand', value: 'Patrick Hand'},
            {innerText: 'Patrick Hand SC', value: 'Patrick Hand SC'},
            {innerText: 'Pattaya', value: 'Pattaya'},
            {innerText: 'Patua One', value: 'Patua One'},
            {innerText: 'Pavanam', value: 'Pavanam'},
            {innerText: 'Paytone One', value: 'Paytone One'},
            {innerText: 'Peddana', value: 'Peddana'},
            {innerText: 'Peralta', value: 'Peralta'},
            {innerText: 'Permanent Marker', value: 'Permanent Marker'},
            {innerText: 'Petemoss', value: 'Petemoss'},
            {innerText: 'Petit Formal Script', value: 'Petit Formal Script'},
            {innerText: 'Petrona', value: 'Petrona'},
            {innerText: 'Philosopher', value: 'Philosopher'},
            {innerText: 'Piazzolla', value: 'Piazzolla'},
            {innerText: 'Piedra', value: 'Piedra'},
            {innerText: 'Pinyon Script', value: 'Pinyon Script'},
            {innerText: 'Pirata One', value: 'Pirata One'},
            {innerText: 'Plaster', value: 'Plaster'},
            {innerText: 'Play', value: 'Play'},
            {innerText: 'Playball', value: 'Playball'},
            {innerText: 'Playfair Display', value: 'Playfair Display'},
            {innerText: 'Playfair Display SC', value: 'Playfair Display SC'},
            {innerText: 'Plus Jakarta Sans', value: 'Plus Jakarta Sans'},
            {innerText: 'Podkova', value: 'Podkova'},
            {innerText: 'Poiret One', value: 'Poiret One'},
            {innerText: 'Poller One', value: 'Poller One'},
            {innerText: 'Poly', value: 'Poly'},
            {innerText: 'Pompiere', value: 'Pompiere'},
            {innerText: 'Pontano Sans', value: 'Pontano Sans'},
            {innerText: 'Poor Story', value: 'Poor Story'},
            {innerText: 'Poppins', value: 'Poppins'},
            {innerText: 'Port Lligat Sans', value: 'Port Lligat Sans'},
            {innerText: 'Port Lligat Slab', value: 'Port Lligat Slab'},
            {innerText: 'Potta One', value: 'Potta One'},
            {innerText: 'Pragati Narrow', value: 'Pragati Narrow'},
            {innerText: 'Praise', value: 'Praise'},
            {innerText: 'Prata', value: 'Prata'},
            {innerText: 'Preahvihear', value: 'Preahvihear'},
            {innerText: 'Press Start 2P', value: 'Press Start 2P'},
            {innerText: 'Pridi', value: 'Pridi'},
            {innerText: 'Princess Sofia', value: 'Princess Sofia'},
            {innerText: 'Prociono', value: 'Prociono'},
            {innerText: 'Prompt', value: 'Prompt'},
            {innerText: 'Prosto One', value: 'Prosto One'},
            {innerText: 'Proza Libre', value: 'Proza Libre'},
            {innerText: 'Public Sans', value: 'Public Sans'},
            {innerText: 'Puppies Play', value: 'Puppies Play'},
            {innerText: 'Puritan', value: 'Puritan'},
            {innerText: 'Purple Purse', value: 'Purple Purse'},
            {innerText: 'Qahiri', value: 'Qahiri'},
            {innerText: 'Quando', value: 'Quando'},
            {innerText: 'Quantico', value: 'Quantico'},
            {innerText: 'Quattrocento', value: 'Quattrocento'},
            {innerText: 'Quattrocento Sans', value: 'Quattrocento Sans'},
            {innerText: 'Questrial', value: 'Questrial'},
            {innerText: 'Quicksand', value: 'Quicksand'},
            {innerText: 'Quintessential', value: 'Quintessential'},
            {innerText: 'Qwigley', value: 'Qwigley'},
            {innerText: 'Qwitcher Grypen', value: 'Qwitcher Grypen'},
            {innerText: 'Racing Sans One', value: 'Racing Sans One'},
            {innerText: 'Radio Canada', value: 'Radio Canada'},
            {innerText: 'Radley', value: 'Radley'},
            {innerText: 'Rajdhani', value: 'Rajdhani'},
            {innerText: 'Rakkas', value: 'Rakkas'},
            {innerText: 'Raleway', value: 'Raleway'},
            {innerText: 'Raleway Dots', value: 'Raleway Dots'},
            {innerText: 'Ramabhadra', value: 'Ramabhadra'},
            {innerText: 'Ramaraja', value: 'Ramaraja'},
            {innerText: 'Rambla', value: 'Rambla'},
            {innerText: 'Rammetto One', value: 'Rammetto One'},
            {innerText: 'Rampart One', value: 'Rampart One'},
            {innerText: 'Ranchers', value: 'Ranchers'},
            {innerText: 'Rancho', value: 'Rancho'},
            {innerText: 'Ranga', value: 'Ranga'},
            {innerText: 'Rasa', value: 'Rasa'},
            {innerText: 'Rationale', value: 'Rationale'},
            {innerText: 'Ravi Prakash', value: 'Ravi Prakash'},
            {innerText: 'Readex Pro', value: 'Readex Pro'},
            {innerText: 'Recursive', value: 'Recursive'},
            {innerText: 'Red Hat Display', value: 'Red Hat Display'},
            {innerText: 'Red Hat Mono', value: 'Red Hat Mono'},
            {innerText: 'Red Hat Text', value: 'Red Hat Text'},
            {innerText: 'Red Rose', value: 'Red Rose'},
            {innerText: 'Redacted', value: 'Redacted'},
            {innerText: 'Redacted Script', value: 'Redacted Script'},
            {innerText: 'Redressed', value: 'Redressed'},
            {innerText: 'Reem Kufi', value: 'Reem Kufi'},
            {innerText: 'Reem Kufi Fun', value: 'Reem Kufi Fun'},
            {innerText: 'Reem Kufi Ink', value: 'Reem Kufi Ink'},
            {innerText: 'Reenie Beanie', value: 'Reenie Beanie'},
            {innerText: 'Reggae One', value: 'Reggae One'},
            {innerText: 'Revalia', value: 'Revalia'},
            {innerText: 'Rhodium Libre', value: 'Rhodium Libre'},
            {innerText: 'Ribeye', value: 'Ribeye'},
            {innerText: 'Ribeye Marrow', value: 'Ribeye Marrow'},
            {innerText: 'Righteous', value: 'Righteous'},
            {innerText: 'Risque', value: 'Risque'},
            {innerText: 'Road Rage', value: 'Road Rage'},
            {innerText: 'Roboto', value: 'Roboto'},
            {innerText: 'Roboto Condensed', value: 'Roboto Condensed'},
            {innerText: 'Roboto Flex', value: 'Roboto Flex'},
            {innerText: 'Roboto Mono', value: 'Roboto Mono'},
            {innerText: 'Roboto Serif', value: 'Roboto Serif'},
            {innerText: 'Roboto Slab', value: 'Roboto Slab'},
            {innerText: 'Rochester', value: 'Rochester'},
            {innerText: 'Rock Salt', value: 'Rock Salt'},
            {innerText: 'RocknRoll One', value: 'RocknRoll One'},
            {innerText: 'Rokkitt', value: 'Rokkitt'},
            {innerText: 'Romanesco', value: 'Romanesco'},
            {innerText: 'Ropa Sans', value: 'Ropa Sans'},
            {innerText: 'Rosario', value: 'Rosario'},
            {innerText: 'Rosarivo', value: 'Rosarivo'},
            {innerText: 'Rouge Script', value: 'Rouge Script'},
            {innerText: 'Rowdies', value: 'Rowdies'},
            {innerText: 'Rozha One', value: 'Rozha One'},
            {innerText: 'Rubik', value: 'Rubik'},
            {innerText: 'Rubik 80s Fade', value: 'Rubik 80s Fade'},
            {innerText: 'Rubik Beastly', value: 'Rubik Beastly'},
            {innerText: 'Rubik Bubbles', value: 'Rubik Bubbles'},
            {innerText: 'Rubik Burned', value: 'Rubik Burned'},
            {innerText: 'Rubik Dirt', value: 'Rubik Dirt'},
            {innerText: 'Rubik Distressed', value: 'Rubik Distressed'},
            {innerText: 'Rubik Gemstones', value: 'Rubik Gemstones'},
            {innerText: 'Rubik Glitch', value: 'Rubik Glitch'},
            {innerText: 'Rubik Iso', value: 'Rubik Iso'},
            {innerText: 'Rubik Marker Hatch', value: 'Rubik Marker Hatch'},
            {innerText: 'Rubik Maze', value: 'Rubik Maze'},
            {innerText: 'Rubik Microbe', value: 'Rubik Microbe'},
            {innerText: 'Rubik Mono One', value: 'Rubik Mono One'},
            {innerText: 'Rubik Moonrocks', value: 'Rubik Moonrocks'},
            {innerText: 'Rubik Puddles', value: 'Rubik Puddles'},
            {innerText: 'Rubik Spray Paint', value: 'Rubik Spray Paint'},
            {innerText: 'Rubik Storm', value: 'Rubik Storm'},
            {innerText: 'Rubik Vinyl', value: 'Rubik Vinyl'},
            {innerText: 'Rubik Wet Paint', value: 'Rubik Wet Paint'},
            {innerText: 'Ruda', value: 'Ruda'},
            {innerText: 'Rufina', value: 'Rufina'},
            {innerText: 'Ruge Boogie', value: 'Ruge Boogie'},
            {innerText: 'Ruluko', value: 'Ruluko'},
            {innerText: 'Rum Raisin', value: 'Rum Raisin'},
            {innerText: 'Ruslan Display', value: 'Ruslan Display'},
            {innerText: 'Russo One', value: 'Russo One'},
            {innerText: 'Ruthie', value: 'Ruthie'},
            {innerText: 'Rye', value: 'Rye'},
            {innerText: 'STIX Two Text', value: 'STIX Two Text'},
            {innerText: 'Sacramento', value: 'Sacramento'},
            {innerText: 'Sahitya', value: 'Sahitya'},
            {innerText: 'Sail', value: 'Sail'},
            {innerText: 'Saira', value: 'Saira'},
            {innerText: 'Saira Condensed', value: 'Saira Condensed'},
            {innerText: 'Saira Extra Condensed', value: 'Saira Extra Condensed'},
            {innerText: 'Saira Semi Condensed', value: 'Saira Semi Condensed'},
            {innerText: 'Saira Stencil One', value: 'Saira Stencil One'},
            {innerText: 'Salsa', value: 'Salsa'},
            {innerText: 'Sanchez', value: 'Sanchez'},
            {innerText: 'Sancreek', value: 'Sancreek'},
            {innerText: 'Sansita', value: 'Sansita'},
            {innerText: 'Sansita Swashed', value: 'Sansita Swashed'},
            {innerText: 'Sarabun', value: 'Sarabun'},
            {innerText: 'Sarala', value: 'Sarala'},
            {innerText: 'Sarina', value: 'Sarina'},
            {innerText: 'Sarpanch', value: 'Sarpanch'},
            {innerText: 'Sassy Frass', value: 'Sassy Frass'},
            {innerText: 'Satisfy', value: 'Satisfy'},
            {innerText: 'Sawarabi Gothic', value: 'Sawarabi Gothic'},
            {innerText: 'Sawarabi Mincho', value: 'Sawarabi Mincho'},
            {innerText: 'Scada', value: 'Scada'},
            {innerText: 'Scheherazade New', value: 'Scheherazade New'},
            {innerText: 'Schoolbell', value: 'Schoolbell'},
            {innerText: 'Scope One', value: 'Scope One'},
            {innerText: 'Seaweed Script', value: 'Seaweed Script'},
            {innerText: 'Secular One', value: 'Secular One'},
            {innerText: 'Sedgwick Ave', value: 'Sedgwick Ave'},
            {innerText: 'Sedgwick Ave Display', value: 'Sedgwick Ave Display'},
            {innerText: 'Sen', value: 'Sen'},
            {innerText: 'Send Flowers', value: 'Send Flowers'},
            {innerText: 'Sevillana', value: 'Sevillana'},
            {innerText: 'Seymour One', value: 'Seymour One'},
            {innerText: 'Shadows Into Light', value: 'Shadows Into Light'},
            {innerText: 'Shadows Into Light Two', value: 'Shadows Into Light Two'},
            {innerText: 'Shalimar', value: 'Shalimar'},
            {innerText: 'Shanti', value: 'Shanti'},
            {innerText: 'Share', value: 'Share'},
            {innerText: 'Share Tech', value: 'Share Tech'},
            {innerText: 'Share Tech Mono', value: 'Share Tech Mono'},
            {innerText: 'Shippori Antique', value: 'Shippori Antique'},
            {innerText: 'Shippori Antique B1', value: 'Shippori Antique B1'},
            {innerText: 'Shippori Mincho', value: 'Shippori Mincho'},
            {innerText: 'Shippori Mincho B1', value: 'Shippori Mincho B1'},
            {innerText: 'Shojumaru', value: 'Shojumaru'},
            {innerText: 'Short Stack', value: 'Short Stack'},
            {innerText: 'Shrikhand', value: 'Shrikhand'},
            {innerText: 'Siemreap', value: 'Siemreap'},
            {innerText: 'Sigmar One', value: 'Sigmar One'},
            {innerText: 'Signika', value: 'Signika'},
            {innerText: 'Signika Negative', value: 'Signika Negative'},
            {innerText: 'Silkscreen', value: 'Silkscreen'},
            {innerText: 'Simonetta', value: 'Simonetta'},
            {innerText: 'Single Day', value: 'Single Day'},
            {innerText: 'Sintony', value: 'Sintony'},
            {innerText: 'Sirin Stencil', value: 'Sirin Stencil'},
            {innerText: 'Six Caps', value: 'Six Caps'},
            {innerText: 'Skranji', value: 'Skranji'},
            {innerText: 'Slabo 13px', value: 'Slabo 13px'},
            {innerText: 'Slabo 27px', value: 'Slabo 27px'},
            {innerText: 'Slackey', value: 'Slackey'},
            {innerText: 'Smokum', value: 'Smokum'},
            {innerText: 'Smooch', value: 'Smooch'},
            {innerText: 'Smooch Sans', value: 'Smooch Sans'},
            {innerText: 'Smythe', value: 'Smythe'},
            {innerText: 'Sniglet', value: 'Sniglet'},
            {innerText: 'Snippet', value: 'Snippet'},
            {innerText: 'Snowburst One', value: 'Snowburst One'},
            {innerText: 'Sofadi One', value: 'Sofadi One'},
            {innerText: 'Sofia', value: 'Sofia'},
            {innerText: 'Sofia Sans', value: 'Sofia Sans'},
            {innerText: 'Sofia Sans Condensed', value: 'Sofia Sans Condensed'},
            {innerText: 'Sofia Sans Extra Condensed', value: 'Sofia Sans Extra Condensed'},
            {innerText: 'Sofia Sans Semi Condensed', value: 'Sofia Sans Semi Condensed'},
            {innerText: 'Solitreo', value: 'Solitreo'},
            {innerText: 'Solway', value: 'Solway'},
            {innerText: 'Song Myung', value: 'Song Myung'},
            {innerText: 'Sono', value: 'Sono'},
            {innerText: 'Sonsie One', value: 'Sonsie One'},
            {innerText: 'Sora', value: 'Sora'},
            {innerText: 'Sorts Mill Goudy', value: 'Sorts Mill Goudy'},
            {innerText: 'Source Code Pro', value: 'Source Code Pro'},
            {innerText: 'Source Sans 3', value: 'Source Sans 3'},
            {innerText: 'Source Sans Pro', value: 'Source Sans Pro'},
            {innerText: 'Source Serif 4', value: 'Source Serif 4'},
            {innerText: 'Source Serif Pro', value: 'Source Serif Pro'},
            {innerText: 'Space Grotesk', value: 'Space Grotesk'},
            {innerText: 'Space Mono', value: 'Space Mono'},
            {innerText: 'Special Elite', value: 'Special Elite'},
            {innerText: 'Spectral', value: 'Spectral'},
            {innerText: 'Spectral SC', value: 'Spectral SC'},
            {innerText: 'Spicy Rice', value: 'Spicy Rice'},
            {innerText: 'Spinnaker', value: 'Spinnaker'},
            {innerText: 'Spirax', value: 'Spirax'},
            {innerText: 'Splash', value: 'Splash'},
            {innerText: 'Spline Sans', value: 'Spline Sans'},
            {innerText: 'Spline Sans Mono', value: 'Spline Sans Mono'},
            {innerText: 'Squada One', value: 'Squada One'},
            {innerText: 'Square Peg', value: 'Square Peg'},
            {innerText: 'Sree Krushnadevaraya', value: 'Sree Krushnadevaraya'},
            {innerText: 'Sriracha', value: 'Sriracha'},
            {innerText: 'Srisakdi', value: 'Srisakdi'},
            {innerText: 'Staatliches', value: 'Staatliches'},
            {innerText: 'Stalemate', value: 'Stalemate'},
            {innerText: 'Stalinist One', value: 'Stalinist One'},
            {innerText: 'Stardos Stencil', value: 'Stardos Stencil'},
            {innerText: 'Stick', value: 'Stick'},
            {innerText: 'Stick No Bills', value: 'Stick No Bills'},
            {innerText: 'Stint Ultra Condensed', value: 'Stint Ultra Condensed'},
            {innerText: 'Stint Ultra Expanded', value: 'Stint Ultra Expanded'},
            {innerText: 'Stoke', value: 'Stoke'},
            {innerText: 'Strait', value: 'Strait'},
            {innerText: 'Style Script', value: 'Style Script'},
            {innerText: 'Stylish', value: 'Stylish'},
            {innerText: 'Sue Ellen Francisco', value: 'Sue Ellen Francisco'},
            {innerText: 'Suez One', value: 'Suez One'},
            {innerText: 'Sulphur Point', value: 'Sulphur Point'},
            {innerText: 'Sumana', value: 'Sumana'},
            {innerText: 'Sunflower', value: 'Sunflower'},
            {innerText: 'Sunshiney', value: 'Sunshiney'},
            {innerText: 'Supermercado One', value: 'Supermercado One'},
            {innerText: 'Sura', value: 'Sura'},
            {innerText: 'Suranna', value: 'Suranna'},
            {innerText: 'Suravaram', value: 'Suravaram'},
            {innerText: 'Suwannaphum', value: 'Suwannaphum'},
            {innerText: 'Swanky and Moo Moo', value: 'Swanky and Moo Moo'},
            {innerText: 'Syncopate', value: 'Syncopate'},
            {innerText: 'Syne', value: 'Syne'},
            {innerText: 'Syne Mono', value: 'Syne Mono'},
            {innerText: 'Syne Tactile', value: 'Syne Tactile'},
            {innerText: 'Tai Heritage Pro', value: 'Tai Heritage Pro'},
            {innerText: 'Tajawal', value: 'Tajawal'},
            {innerText: 'Tangerine', value: 'Tangerine'},
            {innerText: 'Tapestry', value: 'Tapestry'},
            {innerText: 'Taprom', value: 'Taprom'},
            {innerText: 'Tauri', value: 'Tauri'},
            {innerText: 'Taviraj', value: 'Taviraj'},
            {innerText: 'Teko', value: 'Teko'},
            {innerText: 'Telex', value: 'Telex'},
            {innerText: 'Tenali Ramakrishna', value: 'Tenali Ramakrishna'},
            {innerText: 'Tenor Sans', value: 'Tenor Sans'},
            {innerText: 'Text Me One', value: 'Text Me One'},
            {innerText: 'Texturina', value: 'Texturina'},
            {innerText: 'Thasadith', value: 'Thasadith'},
            {innerText: 'The Girl Next Door', value: 'The Girl Next Door'},
            {innerText: 'The Nautigal', value: 'The Nautigal'},
            {innerText: 'Tienne', value: 'Tienne'},
            {innerText: 'Tillana', value: 'Tillana'},
            {innerText: 'Timmana', value: 'Timmana'},
            {innerText: 'Tinos', value: 'Tinos'},
            {innerText: 'Tiro Bangla', value: 'Tiro Bangla'},
            {innerText: 'Tiro Devanagari Hindi', value: 'Tiro Devanagari Hindi'},
            {innerText: 'Tiro Devanagari Marathi', value: 'Tiro Devanagari Marathi'},
            {innerText: 'Tiro Devanagari Sanskrit', value: 'Tiro Devanagari Sanskrit'},
            {innerText: 'Tiro Gurmukhi', value: 'Tiro Gurmukhi'},
            {innerText: 'Tiro Kannada', value: 'Tiro Kannada'},
            {innerText: 'Tiro Tamil', value: 'Tiro Tamil'},
            {innerText: 'Tiro Telugu', value: 'Tiro Telugu'},
            {innerText: 'Titan One', value: 'Titan One'},
            {innerText: 'Titillium Web', value: 'Titillium Web'},
            {innerText: 'Tomorrow', value: 'Tomorrow'},
            {innerText: 'Tourney', value: 'Tourney'},
            {innerText: 'Trade Winds', value: 'Trade Winds'},
            {innerText: 'Train One', value: 'Train One'},
            {innerText: 'Trirong', value: 'Trirong'},
            {innerText: 'Trispace', value: 'Trispace'},
            {innerText: 'Trocchi', value: 'Trocchi'},
            {innerText: 'Trochut', value: 'Trochut'},
            {innerText: 'Truculenta', value: 'Truculenta'},
            {innerText: 'Trykker', value: 'Trykker'},
            {innerText: 'Tulpen One', value: 'Tulpen One'},
            {innerText: 'Turret Road', value: 'Turret Road'},
            {innerText: 'Twinkle Star', value: 'Twinkle Star'},
            {innerText: 'Ubuntu', value: 'Ubuntu'},
            {innerText: 'Ubuntu Condensed', value: 'Ubuntu Condensed'},
            {innerText: "Ubuntu Condensed", value: "Ubuntu Condensed"},
            {innerText: 'Ubuntu Mono', value: 'Ubuntu Mono'},
            {innerText: 'Uchen', value: 'Uchen'},
            {innerText: 'Ultra', value: 'Ultra'},
            {innerText: 'Unbounded', value: 'Unbounded'},
            {innerText: 'Uncial Antiqua', value: 'Uncial Antiqua'},
            {innerText: 'Underdog', value: 'Underdog'},
            {innerText: 'Unica One', value: 'Unica One'},
            {innerText: 'UnifrakturCook', value: 'UnifrakturCook'},
            {innerText: 'UnifrakturMaguntia', value: 'UnifrakturMaguntia'},
            {innerText: 'Unkempt', value: 'Unkempt'},
            {innerText: 'Unlock', value: 'Unlock'},
            {innerText: 'Unna', value: 'Unna'},
            {innerText: 'Updock', value: 'Updock'},
            {innerText: 'Urbanist', value: 'Urbanist'},
            {innerText: 'VT323', value: 'VT323'},
            {innerText: 'Vampiro One', value: 'Vampiro One'},
            {innerText: 'Varela', value: 'Varela'},
            {innerText: 'Varela Round', value: 'Varela Round'},
            {innerText: 'Varta', value: 'Varta'},
            {innerText: 'Vast Shadow', value: 'Vast Shadow'},
            {innerText: 'Vazirmatn', value: 'Vazirmatn'},
            {innerText: 'Vesper Libre', value: 'Vesper Libre'},
            {innerText: 'Viaoda Libre', value: 'Viaoda Libre'},
            {innerText: 'Vibes', value: 'Vibes'},
            {innerText: 'Vibur', value: 'Vibur'},
            {innerText: 'Vidaloka', value: 'Vidaloka'},
            {innerText: 'Viga', value: 'Viga'},
            {innerText: 'Voces', value: 'Voces'},
            {innerText: 'Volkhov', value: 'Volkhov'},
            {innerText: 'Vollkorn', value: 'Vollkorn'},
            {innerText: 'Vollkorn SC', value: 'Vollkorn SC'},
            {innerText: 'Voltaire', value: 'Voltaire'},
            {innerText: 'Vujahday Script', value: 'Vujahday Script'},
            {innerText: 'Waiting for the Sunrise', value: 'Waiting for the Sunrise'},
            {innerText: 'Wallpoet', value: 'Wallpoet'},
            {innerText: 'Walter Turncoat', value: 'Walter Turncoat'},
            {innerText: 'Warnes', value: 'Warnes'},
            {innerText: 'Water Brush', value: 'Water Brush'},
            {innerText: 'Waterfall', value: 'Waterfall'},
            {innerText: 'Wellfleet', value: 'Wellfleet'},
            {innerText: 'Wendy One', value: 'Wendy One'},
            {innerText: 'Whisper', value: 'Whisper'},
            {innerText: 'WindSong', value: 'WindSong'},
            {innerText: 'Wire One', value: 'Wire One'},
            {innerText: 'Work Sans', value: 'Work Sans'},
            {innerText: 'Xanh Mono', value: 'Xanh Mono'},
            {innerText: 'Yaldevi', value: 'Yaldevi'},
            {innerText: 'Yanone Kaffeesatz', value: 'Yanone Kaffeesatz'},
            {innerText: 'Yantramanav', value: 'Yantramanav'},
            {innerText: 'Yatra One', value: 'Yatra One'},
            {innerText: 'Yellowtail', value: 'Yellowtail'},
            {innerText: 'Yeon Sung', value: 'Yeon Sung'},
            {innerText: 'Yeseva One', value: 'Yeseva One'},
            {innerText: 'Yesteryear', value: 'Yesteryear'},
            {innerText: 'Yomogi', value: 'Yomogi'},
            {innerText: 'Yrsa', value: 'Yrsa'},
            {innerText: 'Yuji Boku', value: 'Yuji Boku'},
            {innerText: 'Yuji Mai', value: 'Yuji Mai'},
            {innerText: 'Yuji Syuku', value: 'Yuji Syuku'},
            {innerText: 'Yusei Magic', value: 'Yusei Magic'},
            {innerText: 'ZCOOL KuaiLe', value: 'ZCOOL KuaiLe'},
            {innerText: 'ZCOOL QingKe HuangYou', value: 'ZCOOL QingKe HuangYou'},
            {innerText: 'ZCOOL XiaoWei', value: 'ZCOOL XiaoWei'},
            {innerText: 'Zen Antique', value: 'Zen Antique'},
            {innerText: 'Zen Antique Soft', value: 'Zen Antique Soft'},
            {innerText: 'Zen Dots', value: 'Zen Dots'},
            {innerText: 'Zen Kaku Gothic Antique', value: 'Zen Kaku Gothic Antique'},
            {innerText: 'Zen Kaku Gothic New', value: 'Zen Kaku Gothic New'},
            {innerText: 'Zen Kurenaido', value: 'Zen Kurenaido'},
            {innerText: 'Zen Loop', value: 'Zen Loop'},
            {innerText: 'Zen Maru Gothic', value: 'Zen Maru Gothic'},
            {innerText: 'Zen Old Mincho', value: 'Zen Old Mincho'},
            {innerText: 'Zen Tokyo Zoo', value: 'Zen Tokyo Zoo'},
            {innerText: 'Zeyada', value: 'Zeyada'},
            {innerText: 'Zhi Mang Xing', value: 'Zhi Mang Xing'},
            {innerText: 'Zilla Slab', value: 'Zilla Slab'},
            {innerText: 'Zilla Slab Highlight', value: 'Zilla Slab Highlight'},
            {innerText: 'Alef Hebrew', value: 'Alef Hebrew'},
            {innerText: 'Droid Arabic Kufi', value: 'Droid Arabic Kufi'},
            {innerText: 'Droid Arabic Naskh', value: 'Droid Arabic Naskh'},
            {innerText: 'Noto Kufi Arabic', value: 'Noto Kufi Arabic'},
            {innerText: 'Noto Naskh Arabic', value: 'Noto Naskh Arabic'},
            {innerText: 'Noto Sans Hebrew', value: 'Noto Sans Hebrew'},
            {innerText: 'Open Sans Hebrew', value: 'Open Sans Hebrew'},
            {innerText: 'Open Sans Hebrew Condensed', value: 'Open Sans Hebrew Condensed'},
         ],
    }
]
/*--------- Decoration Data --------------*/ 
export const decorationData = [
    {
        title: 'decoration',
        key: 'decoration',
        selectData: [
            {
                innerText: 'default',
                value: '',
            },
            {
                innerText: 'underline',
                value: 'underline',
            },
            {
                innerText: 'Overline',
                value: 'overline',
            },
            {
                innerText: 'Line through',
                value: 'line-through'
            },
            {
              innerText: 'none',
              value: 'none'
            }
        ]
    }
]
/*--------- style Data --------------*/ 
export const styleData = [
    {
        title: 'style',
        key: 'style',
        selectData: [
            {
                innerText: 'Default',
                value: '',
            },
            {
                innerText: 'normal',
                value: 'normal',
            },
            {
                innerText: 'italic',
                value: 'italic',
            },
            {
                innerText: 'oblique',
                value: 'oblique',
            },
        ]
    }
]

/*--------- transform Data --------------*/ 
export const transformData = [
    {
        title: 'transform',
        key: 'transform',
        selectData: [
            {
                innerText: 'Default',
                value: '',
            },
            {
                innerText: 'uppercase',
                value: 'uppercase',
            },
            {
                innerText: 'lowercase',
                value: 'lowercase',
            },
            {
                innerText: 'capitalize',
                value: 'capitalize',
            },
            {
                innerText: 'normal',
                value: 'none',
            },
        ]
    }
]

/*--------- weight Data --------------*/ 
export const weightData = [
    {
        title: 'weight',
        key: 'weight',
        selectData: [
            {
                innerText: '100 (Thin)',
                value: '100',
            },
            {
                innerText: '200 (Extra Light)',
                value: '200',
            },
            {
                innerText: '300 (Light)',
                value: '300',
            },
            {
                innerText: '400 (Normal)',
                value: '400',
            },
            {
                innerText: '500 (Medium)',
                value: '500',
            },
            {
                innerText: '600 (Semi Bold)',
                value: '600',
            },
            {
                innerText: '700 (Bold)',
                value: '700',
            },
            {
                innerText: '800 (Extra Bold)',
                value: '800',
            },
            {
                innerText: '900 (Black)',
                value: '900',
            },
            {
                innerText: 'Default',
                value: '',
            },
            {
                innerText: 'Normal',
                value: 'normal'
            },
            {
                innerText: 'Bold',
                value: 'bold'
            },
        ]
    }
]

/*[============== input range data  ==============]*/

export const fontSizeData = {
    title: 'Size',
    key: 'size',
    maxValue: '200',
    defaultValue: 1,
    minValue: 1,
}

export const lineHeightData = {
    title: 'Line-Height',
    key: 'lineHeight',
    maxValue: '100',
    defaultValue: 0,
    minValue: 0,
}

export const letterSpacingData = {
    title: 'Letter Spacing',
    key: 'letterSpacing',
    maxValue: '100',
    defaultValue: 30,
    minValue: 0,
}

export const wordSpacingData = {
    title: 'Word Spacing',
    key: 'wordSpacing',
    maxValue: '100',
    defaultValue: 0,
    minValue: 0,
}

